/* DEV-only Apps Script entry points. No generic mutation and no PROD fallback. */
function _r1aCloudOptions(){
  var store=_s17CloudStore();
  store.withLock=function(fn){var lock=LockService.getScriptLock();lock.waitLock(30000);try{return fn();}finally{lock.releaseLock();}};
  return {store:store,config:{environment:'DEV',sheetId:R1A_BOUND_DEV_SHEET_ID},actorEmail:function(){return Session.getActiveUser().getEmail();},effectiveUserEmail:function(){return Session.getEffectiveUser().getEmail();},reads:{officeHome:_s17OfficeToday,jobOverview:_s17JobOverview,operationalQueue:_s17OperationalQueue,releaseModes:_s17AdminReleaseModes,systemStatus:_s17AdminSystemStatus,auditHistory:_s17AuditHistory,actionAvailability:_s17ActionAvailability,taskActionAvailability:_s17TaskActionAvailability},services:_r1sServices()};
}
function appSheetR1Read(requestJson){try{return JSON.stringify(_r1aCreate(_r1aCloudOptions()).read(JSON.parse(requestJson)));}catch(e){return JSON.stringify({ok:false,error:e.code||e.message||'R1A_REFUSED'});}}
function appSheetR1Command(requestJson){try{return JSON.stringify(_r1aCreate(_r1aCloudOptions()).command(JSON.parse(requestJson)));}catch(e){return JSON.stringify({ok:false,error:e.code||e.message||'R1A_REFUSED'});}}

/* Namespaced DEV synthetic fixtures for AppSheet command smokes. Exact DEV sheet only. */
function _r1aFixtureResult(name,pass,detail){var r={test:name,pass:pass,detail:detail};console.log(JSON.stringify(r,null,2));return r;}
function _r1aFixtureIns(store,table,row){if(!store.get(table,row.id))store.insert(table,row);}

function runR1APrepareDepositConfirmFixture(){
  var store=_r1aCloudOptions().store,n='2026-11-01T00:00:00.000Z',jobId='J-r1a-deposit';
  _r1aFixtureIns(store,'Jobs',{id:jobId,job_id:'SS-R1A-DEP',customer_id:'CUST-r1a-dep',display_name:'R1A Deposit Confirm DEV',sold_submission_id:'R1A-sold-dep',booking_submission_id:'R1A-booking-dep',sold_at:n,salesperson_id:null,lead_source:'R1A',quote_reference:'Q-R1A-DEP',presale_file_id:null,finance_route:'Standard',contract_status:'Signed',contract_id:'C-R1A-DEP',contract_signed_at:n,contract_evidence_id:null,original_net_pence:400000,original_vat_pence:80000,original_gross_pence:480000,approved_change_pence:null,current_contract_gross_pence:480000,valuation_basis:'Standard',sold_booking_match_status:'Match',customer_details_verified_at:n,customer_details_verified_by:'PERSON-tanya',deposit_bank_confirmed_at:null,deposit_bank_confirmed_by:null,deposit_bank_reference:null,roof_required:false,electrical_required:false,scaffold_required:false,workflow_stage:'Booked',booking_approved_at:n,booking_approved_by:'PERSON-tanya',operational_complete_at:null,operational_complete_by:null,customer_happy_at:null,customer_happy_by:null,handover_status:'NotReady',financial_status:'Pending',cancellation_at:null,cancellation_by:null,cancellation_reason:null,archived_at:null,next_action_at:n,account_policy_version:null,pilot_job:true,release_scope:'R1',created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',source_record_id:null,commit_id:'R1A-DEP'});
  _r1aFixtureIns(store,'InvoiceStages',{id:'IS-'+jobId+'-deposit',job_id:jobId,stage:'deposit',amount_net_pence:100000,vat_pence:20000,gross_pence:120000,due_date:null,status:'Pending',xero_invoice_id:null,invoice_number:null,xero_contact_id:null,reference:null,request_id:null,last_synced_at:null,source_status:null,sent_at:null,cancelled_at:null,created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',commit_id:'R1A-DEP'});
  var job=store.get('Jobs',jobId);
  return _r1aFixtureResult('R1A deposit fixture',!!job&&!!store.get('InvoiceStages','IS-'+jobId+'-deposit')&&!job.deposit_bank_confirmed_at,{job_id:jobId,expected_version:Number(job.version)});
}

function runR1APrepareOperationalCompleteFixture(){
  var store=_r1aCloudOptions().store,n='2026-11-11T12:00:00.000Z',jobId='J-r1a-opcomplete';
  _r1aFixtureIns(store,'Jobs',{id:jobId,job_id:'SS-R1A-OPC',customer_id:'CUST-r1a-opc',display_name:'R1A Operational Complete DEV',sold_submission_id:'R1A-sold-opc',booking_submission_id:'R1A-booking-opc',sold_at:n,salesperson_id:null,lead_source:'R1A',quote_reference:'Q-R1A-OPC',presale_file_id:null,finance_route:'Standard',contract_status:'Signed',contract_id:'C-R1A-OPC',contract_signed_at:n,contract_evidence_id:null,original_net_pence:400000,original_vat_pence:80000,original_gross_pence:480000,approved_change_pence:null,current_contract_gross_pence:480000,valuation_basis:'Standard',sold_booking_match_status:'Match',customer_details_verified_at:n,customer_details_verified_by:'PERSON-tanya',deposit_bank_confirmed_at:n,deposit_bank_confirmed_by:'PERSON-ben',deposit_bank_reference:'R1A-DEP',roof_required:true,electrical_required:false,scaffold_required:false,workflow_stage:'Aftercare',booking_approved_at:n,booking_approved_by:'PERSON-tanya',operational_complete_at:null,operational_complete_by:null,customer_happy_at:'2026-11-09T10:00:00.000Z',customer_happy_by:'PERSON-tanya',handover_status:'NotReady',financial_status:'Pending',cancellation_at:null,cancellation_by:null,cancellation_reason:null,archived_at:null,next_action_at:n,account_policy_version:null,pilot_job:true,release_scope:'R1',created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',source_record_id:null,commit_id:'R1A-OPC'});
  _r1aFixtureIns(store,'WorkPackages',{id:'WP-r1a-opc-roof',job_id:jobId,trade:'Roof',required:true,planned_start:'2026-11-05',planned_end:'2026-11-06',actual_start:'2026-11-05',actual_end:'2026-11-06',status:'ConfirmedComplete',completion_outcome:'Complete',installer_confirmation_at:'2026-11-09T10:00:00.000Z',installer_confirmation_by:'PERSON-tanya',commissioning_required:true,sequence:1,revision:1,created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',commit_id:'R1A-OPC'});
  _r1aFixtureIns(store,'Allocations',{id:'ALLOC-r1a-opc',work_package_id:'WP-r1a-opc-roof',person_id:'PERSON-installer-a',role:'Lead',active:true,created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',commit_id:'R1A-OPC'});
  _r1aFixtureIns(store,'CommissioningSubmissions',{id:'CS-r1a-opc',job_id:jobId,work_package_id:'WP-r1a-opc-roof',allocation_id:'ALLOC-r1a-opc',installer_id:'PERSON-installer-a',template_version:'R1A-sample',status:'Accepted',submitted_at:'2026-11-09T09:00:00.000Z',reviewed_at:'2026-11-09T10:00:00.000Z',reviewed_by:'PERSON-tanya',review_notes:'R1A synthetic accepted',created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,commit_id:'R1A-OPC'});
  // Do NOT create a duplicate GHL01 template — S02 seed already provides TPL-GHL01
  _r1aFixtureIns(store,'Tasks',{id:'TASK-r1a-opc-access',job_id:jobId,template_code:'R1A-ACCESS',instance_key:'R1A-OPC-ACCESS',group:'Aftercare',title:'R1A office access (DEV)',owner_id:'PERSON-tanya',backup_id:null,related_entity_type:'Jobs',related_entity_id:jobId,due_at:n,original_due_at:n,priority:2,status:'Open',blocking_reason:null,next_followup_at:null,completed_at:null,completed_by:null,completion_note:null,evidence_id:null,revision_required:false,created_rule_version:'R1A-1.0',created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',commit_id:'R1A-OPC'});
  // Reset job if a prior failed command left it partially mutated (operational_complete_at set without GHL task)
  var job=store.get('Jobs',jobId);
  if(job&&job.operational_complete_at&&!store.list('GHLTasks').some(function(g){return g.job_id===jobId&&g.task_id;})){
    store.update('Jobs',jobId,{workflow_stage:'Aftercare',operational_complete_at:null,operational_complete_by:null,updated_at:n,updated_by:'R1A-fixture',version:1});
    job=store.get('Jobs',jobId);
  }
  return _r1aFixtureResult('R1A operational-complete fixture',!!job&&!job.operational_complete_at&&!!store.get('WorkPackages','WP-r1a-opc-roof'),{job_id:jobId,expected_version:Number(job.version)});
}

function runR1APrepareBookingGatesFixture(){
  var store=_r1aCloudOptions().store,n='2026-09-06T00:00:00.000Z',jobId='J-r1a-booking';
  _r1aFixtureIns(store,'Customers',{id:'CUST-r1a-bkg',first_name:'R1A',last_name:'Booking',address_line1:'1 Pilot Lane',address_line2:'',town:'Testville',postcode:'TS1 1AA',email:'r1a-booking@test.example.invalid',phone:'07000000000',alternate_contact:null,contact_notes:null,created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',source_record_id:null,commit_id:'R1A-BKG'});
  _r1aFixtureIns(store,'Jobs',{id:jobId,job_id:'SS-R1A-BKG',customer_id:'CUST-r1a-bkg',display_name:'R1A Booking Gates DEV',sold_submission_id:'R1A-sold-bkg',booking_submission_id:'R1A-booking-bkg',sold_at:n,salesperson_id:null,lead_source:'R1A',quote_reference:'Q-R1A-BKG',presale_file_id:null,finance_route:'Standard',contract_status:'Signed',contract_id:'C-R1A-BKG',contract_signed_at:n,contract_evidence_id:null,original_net_pence:400000,original_vat_pence:80000,original_gross_pence:480000,approved_change_pence:null,current_contract_gross_pence:480000,valuation_basis:'Standard',sold_booking_match_status:'Match',customer_details_verified_at:n,customer_details_verified_by:'PERSON-tanya',deposit_bank_confirmed_at:n,deposit_bank_confirmed_by:'PERSON-ben',deposit_bank_reference:'R1A-BKG-DEP',roof_required:false,electrical_required:false,scaffold_required:false,workflow_stage:'BookingInProgress',booking_approved_at:null,booking_approved_by:null,operational_complete_at:null,operational_complete_by:null,customer_happy_at:null,customer_happy_by:null,handover_status:'NotReady',financial_status:'Pending',cancellation_at:null,cancellation_by:null,cancellation_reason:null,archived_at:null,next_action_at:n,account_policy_version:null,pilot_job:true,release_scope:'R1',created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',source_record_id:null,commit_id:'R1A-BKG'});
  _r1aFixtureIns(store,'Tasks',{id:'TASK-r1a-bkg-access',job_id:jobId,template_code:'R1A-ACCESS',instance_key:'R1A-BKG-ACCESS',group:'Booking',title:'R1A office access (DEV)',owner_id:'PERSON-tanya',backup_id:null,related_entity_type:'Jobs',related_entity_id:jobId,due_at:n,original_due_at:n,priority:2,status:'Open',blocking_reason:null,next_followup_at:null,completed_at:null,completed_by:null,completion_note:null,evidence_id:null,revision_required:false,created_rule_version:'R1A-1.0',created_at:n,created_by:'R1A-fixture',updated_at:n,updated_by:'R1A-fixture',version:1,source_system:'R1A-fixture',commit_id:'R1A-BKG'});
  var job=store.get('Jobs',jobId);
  return _r1aFixtureResult('R1A booking-gates fixture',!!job&&job.pilot_job===true&&job.workflow_stage==='BookingInProgress',{job_id:jobId,expected_version:Number(job.version)});
}
