const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),cp=require('node:child_process');
const schema=require('../schema/tables.json'),seed=require('../schema/config-seed.json');
const core=require('../r1-appsheet/adapter.js'),req=require('../r1-appsheet/request-row.js'),ops=require('../r1-appsheet/operations-contract.js');
const requestSource=fs.readFileSync('r1-appsheet/operations-requests.js','utf8');
function fixture(){
  const tables=Object.fromEntries(schema.tables.map(t=>[t.name,[]]));let locked=false;
  const s={tables,getSheetId:()=>core.R1A_BOUND_DEV_SHEET_ID,getEnvironment:()=> 'DEV',list:n=>structuredClone(tables[n]||[]),get(n,id){const rows=this.list(n).filter(r=>r.id===id);assert.ok(rows.length<=1);return rows[0]||null;},insert(n,r){assert.ok(!this.get(n,r.id));check(n,r);tables[n].push(structuredClone(r));},update(n,id,p){check(n,p);const r=tables[n].find(r=>r.id===id);assert.ok(r,n+'/'+id);Object.assign(r,structuredClone(p));},withLock(fn){assert.equal(locked,false);locked=true;try{return fn();}finally{locked=false;}}};
  function check(n,r){const t=schema.tables.find(t=>t.name===n);assert.ok(t,n);for(const k of Object.keys(r))assert.ok(t.columns.some(c=>c.name===k),n+'.'+k);}
  for(const n of ['Settings','TaskTemplates','ReleaseModes','People','PersonRoles','Companies','Products','StockLocations'])for(const r of seed[n]||[])s.insert(n,{...r,version:1});
  for(const fn of ['FN03','FN05','FN06','FN07'])s.update('ReleaseModes','RM-'+fn,{mode:'Automated',authorised_job_scope:'Pilot'});
  for(const [id,role] of [['installer','Installer'],['other','Installer'],['office','Office'],['store','Store'],['admin','Admin'],['director','Director']]){s.insert('People',{id,email:id+'@test.invalid',active:true,display_name:id,role,version:1});s.insert('PersonRoles',{id:'role-'+id,person_id:id,role,active:true,version:1});}
  s.insert('Jobs',{id:'J',job_id:'SS-DEV',display_name:'DEV job',pilot_job:true,release_scope:'R3',workflow_stage:'InProgress',version:1});
  s.insert('WorkPackages',{id:'WP',job_id:'J',trade:'Roof',required:true,status:'Scheduled',commissioning_required:true,version:1,sequence:1,revision:1});
  s.insert('Allocations',{id:'AL',work_package_id:'WP',person_id:'installer',role:'Lead',active:true,version:1});
  s.insert('Jobs',{id:'JM',job_id:'SS-MAT',display_name:'DEV materials',pilot_job:true,release_scope:'R2',workflow_stage:'Booked',version:1});
  s.insert('Orders',{id:'ORDER',job_id:'JM',merchant_id:'COMP-greentech',status:'Confirmed',version:1,revision:1,requested_delivery_date:'2026-09-20'});
  for(let i=1;i<=3;i++)s.insert('OrderLines',{id:'LINE'+i,order_id:'ORDER',product_id:'PROD-P460',quantity:10,cancelled_quantity:0,description_snapshot:'Panels',unit:'Each'});
  s.insert('Deliveries',{id:'DEL',order_id:'ORDER',receipt_status:'Expected'});
  s.insert('StockMovements',{id:'OPEN',product_id:'PROD-P460',quantity:20,from_location_id:'LOC-external',to_location_id:'LOC-store',movement_type:'Receipt',idempotency_key:'OPEN'});
  const api=(actor='installer')=>core._r1aCreate({store:s,config:{environment:'DEV',sheetId:s.getSheetId()},actorEmail:()=>actor+'@test.invalid'});
  return{s,tables,api};
}
const cmd=(type,extra={})=>({command_type:type,command_id:'CMD-'+type,job_id:'J',work_package_id:'WP',expected_version:1,payload:{},...extra});
function receive(extra={}){return{command_type:'GOODS_IN_RECEIVE',command_id:'RECEIVE',job_id:'JM',expected_version:1,payload:{delivery_id:'DEL',delivery_note_reference:'NOTE-1',lines:[{order_line_id:'LINE1',quantity_good:10},{order_line_id:'LINE2',quantity_good:8,quantity_damaged:2},{order_line_id:'LINE3',quantity_good:5,quantity_short:5}]},...extra};}
const quarantine=(extra={})=>({command_type:'STOCK_QUARANTINE',command_id:'QUAR',expected_version:1,payload:{product_id:'PROD-P460',quantity:2,expected_balance:20,reason:'Cracked panel'},...extra});
const snapshot=f=>JSON.stringify(f.tables);
function noWrite(f,fn,re){const before=snapshot(f);assert.throws(fn,re);assert.equal(snapshot(f),before);}
function requestContext(){const c=vm.createContext({console,require,Number,Date,JSON,Array,Object,String,Error,RegExp});vm.runInContext(fs.readFileSync('r1-appsheet/operations-contract.js','utf8').replace(/^if\(typeof module[^\n]+/gm,''),c);vm.runInContext(requestSource.replace(/^if\(typeof module[^\n]+/gm,''),c);vm.runInContext(fs.readFileSync('r1-appsheet/request-row.js','utf8').replace(/if \(typeof module !== 'undefined'\) module.exports = \{[\s\S]*$/,''),c);return c;}
function installerRow(extra={}){return{id:'REQ',command_id:'MOBILE-1',command_type:'IW_START',job_id:'J',work_package_id:'WP',expected_version:1,submitted_by:'installer@test.invalid',status:'Ready',...extra};}
test('ops: existing reads retained, no redundant MY_WORK; ten new commands and three reads',()=>{assert.equal(core.R1A_BOUND_READS.length,18);assert.equal(core.R1A_BOUND_COMMANDS.length,26);assert.ok(!core.R1A_BOUND_READS.includes('INSTALLER_MY_WORK'));assert.equal(Object.keys(ops.R1C_COMMANDS).length,10);});
test('ops: request row USEREMAIL actor, discriminator, separate editable identity never trusted',()=>{const c=requestContext(),f=fixture();let row=installerRow({actor:'admin',requested_by:'admin@test.invalid'});const deps={sessionEmail:'installer@test.invalid',readRows:()=>[row],dispatch:(r,email)=>{assert.equal(email,'installer@test.invalid');return f.api().command(JSON.parse(JSON.stringify(r)));}};const r=c._r1aCommandFromRequestRow('IW_START','REQ','installer@test.invalid',deps);assert.equal(r.result.status,'InProgress');assert.equal(f.s.get('WorkPackages','WP').updated_by,'installer');assert.throws(()=>c._r1aCommandFromRequestRow('IW_START','REQ','admin@test.invalid',deps),/ACTOR_MISMATCH/);row=installerRow({command_type:'IW_PROGRESS'});assert.throws(()=>c._r1aCommandFromRequestRow('IW_START','REQ','installer@test.invalid',deps),/COMMAND_TYPE_MISMATCH/);});
for(const [label,edit,actor,regex] of [
 ['missing auth',f=>{},'',/AUTHENTICATED|UNKNOWN/],['inactive',f=>f.s.update('People','installer',{active:false}),'installer',/INACTIVE/],['duplicate identity',f=>f.s.insert('People',{id:'dup',email:'installer@test.invalid',active:true}),'installer',/DUPLICATE/],['role',f=>{},'store',/ROLE_DENIED/],['assignment',f=>{},'other',/ASSIGNMENT/],['office reason',f=>{},'office',/REASON/],['mode',f=>f.s.update('ReleaseModes','RM-FN06',{mode:'Disabled'}),'installer',/MODE/],['cancelled',f=>f.s.update('Jobs','J',{workflow_stage:'Cancelled'}),'installer',/NOT_ACTIONABLE/],['archive',f=>f.s.update('Jobs','J',{archived_at:'2026-09-01'}),'installer',/NOT_ACTIONABLE/],['nonpilot',f=>f.s.update('Jobs','J',{pilot_job:false}),'installer',/PILOT/],['prod',f=>{f.s.getEnvironment=()=> 'PROD';},'installer',/DEV_ONLY/]])test('ops guard: '+label,()=>{const f=fixture();edit(f);noWrite(f,()=>f.api(actor).command(cmd('IW_START')),regex);});
test('ops: direct actor forgery/extra fields rejected; office reason accepted and audited',()=>{const f=fixture();noWrite(f,()=>f.api().command(cmd('IW_START',{payload:{actor:'admin'}})),/INVALID_FIELDS/);noWrite(f,()=>f.api().command({...cmd('IW_START'),actor:'admin'}),/INVALID_FIELDS/);const r=f.api('office').command(cmd('IW_START',{payload:{reason:'Installer phoned in'}}));assert.equal(r.actor_id,'office');assert.equal(f.s.get('AuditEvents','AE-R1C-CMD-IW_START').initiating_actor,'office');});
test('ops: start exact replay, changed actor/payload/version rejected, stale has no prepared journal',()=>{const f=fixture(),r=cmd('IW_START');f.api().command(r);const after=snapshot(f);assert.equal(f.api().command(r).result.replay,true);assert.equal(snapshot(f),after);noWrite(f,()=>f.api().command({...r,expected_version:2}),/COMMAND_CONFLICT/);noWrite(f,()=>f.api().command({...r,payload:{reason:'changed'}}),/COMMAND_CONFLICT/);noWrite(f,()=>f.api().command({...r,command_id:'NEW'}),/STALE/);});
for(const version of [undefined,null,0,-1,1.5,true,'','1.5','NaN'])test('ops invalid version '+String(version),()=>{const f=fixture();noWrite(f,()=>f.api().command(cmd('IW_START',{expected_version:version})),/VERSION/);});
test('ops: progress consumes package version; invalid later evidence cannot partially write',()=>{const f=fixture();const r=cmd('IW_PROGRESS',{payload:{note:'Rails fitted',evidence:[{drive_file_id:'file-1',filename:'rails.jpg'}]}});assert.equal(f.api().command(r).result.expected_version,2);assert.equal(f.s.list('Evidence').length,1);assert.equal(f.api().command(r).result.replay,true);noWrite(f,()=>f.api().command(cmd('IW_PROGRESS',{command_id:'BAD',expected_version:2,payload:{evidence:[{drive_file_id:'file-2'},{filename:'no id'}]}})),/FILE_REQUIRED/);});
test('ops: cross-job file denial scans entire evidence table',()=>{const f=fixture();f.s.insert('Evidence',{id:'foreign',job_id:'OTHER',drive_file_id:'file-1'});noWrite(f,()=>f.api().command(cmd('IW_PROGRESS',{payload:{evidence:[{drive_file_id:'file-1'}]}})),/CROSS_JOB/);});
test('ops: complete report is not office confirmation; return retains original installer and one return per replay',()=>{for(const outcome of ['Complete','ReturnRequired']){const f=fixture(),r=cmd('IW_REPORT_COMPLETION',{payload:{outcome,actual_end:'2026-09-01',return_reason:'Panels missing'}});const res=f.api().command(r).result;assert.equal(res.status,outcome==='Complete'?'ReportedComplete':'ReturnRequired');assert.ok(!f.s.get('WorkPackages','WP').installer_confirmation_at);f.api().command(r);assert.equal(f.s.list('WorkPackages').length,outcome==='Complete'?1:2);if(outcome==='ReturnRequired'){assert.equal(f.s.list('Allocations').find(a=>a.work_package_id===res.return_package_id).person_id,'installer');assert.equal(f.s.list('Issues')[0].type,'Remedial');assert.ok(!res.issue);}}});
for(const [type,payload] of [['IW_REPORT_PROBLEM',{category:'Safety',description:'Loose tiles'}],['IW_REPORT_VARIATION',{description:'Bird mesh requested'}]])test('ops: '+type+' audited/versioned without private response data',()=>{const f=fixture(),r=cmd(type,{payload});const res=f.api().command(r).result;assert.equal(res.expected_version,2);assert.ok(res.issue_id);assert.equal(res.issue,undefined);assert.equal(f.api().command(r).result.replay,true);assert.equal(f.s.list('Issues').length,1);});
function draft(f){return f.api().command(cmd('IW_COMMISSIONING_DRAFT',{payload:{evidence:[{drive_file_id:'commissioning-1'}]}})).result;}
test('ops: commissioning evidence draft/submit/return/supersede keeps history and versions',()=>{const f=fixture(),d=draft(f);assert.equal(d.template_version,'NOT_CONFIGURED');noWrite(f,()=>f.api().command(cmd('IW_COMMISSIONING_DRAFT',{command_id:'D2',expected_version:2,payload:{evidence:[{drive_file_id:'new'}]}})),/VERSION|STALE_SUBMISSION/);const submit=cmd('IW_COMMISSIONING_SUBMIT',{payload:{submission_id:d.submission_id}});assert.equal(f.api().command(submit).result.status,'Submitted');assert.equal(f.api().command(submit).result.replay,true);noWrite(f,()=>f.api('office').command(cmd('COMMISSIONING_REVIEW',{expected_version:2,payload:{submission_id:d.submission_id,status:'Accepted',review_notes:'Reviewed'}})),/APPROVED_TEMPLATE/);const review=cmd('COMMISSIONING_REVIEW',{expected_version:2,payload:{submission_id:d.submission_id,status:'Returned',review_notes:'Photo unclear'}});assert.equal(f.api('office').command(review).result.status,'Returned');const returned=f.s.get('CommissioningSubmissions',d.submission_id);const res=f.api().command(cmd('IW_COMMISSIONING_DRAFT',{command_id:'D2',expected_version:2,payload:{submission_id:returned.id,expected_submission_version:returned.version,evidence:[{drive_file_id:'commissioning-1'}]}})).result;assert.notEqual(res.submission_id,returned.id);assert.deepEqual(f.s.get('CommissioningSubmissions',returned.id),returned);assert.equal(f.s.list('Evidence').length,2);assert.ok(f.s.list('Evidence').some(e=>e.submission_id===res.submission_id));});
test('ops: unapproved questions and installer review denied; approved existing schema questions can be answered and reviewed',()=>{const f=fixture();noWrite(f,()=>f.api().command(cmd('IW_COMMISSIONING_DRAFT',{payload:{answers:[{question_key:'invented',value_boolean:true}]}})),/APPROVED_QUESTION/);f.s.insert('CommissioningTemplates',{id:'TPL',trade:'Roof',active:true,approved_by:'admin',approved_at:'2026-09-01',template_version:'APPROVED-1'});f.s.insert('CommissioningQuestions',{id:'Q',template_id:'TPL',question_key:'existing_check',data_type:'Boolean'});const d=f.api().command(cmd('IW_COMMISSIONING_DRAFT',{payload:{answers:[{question_key:'existing_check',value_boolean:true}]}})).result;assert.equal(d.template_version,'APPROVED-1');f.api().command(cmd('IW_COMMISSIONING_SUBMIT',{payload:{submission_id:d.submission_id}}));const review=cmd('COMMISSIONING_REVIEW',{expected_version:2,payload:{submission_id:d.submission_id,status:'Accepted',review_notes:'Technical review completed'}});noWrite(f,()=>f.api().command(review),/ROLE/);f.api('office').command(review);assert.equal(f.s.get('CommissioningSubmissions',d.submission_id).reviewed_by,'office');assert.equal(f.api('office').command(review).result.replay,true);});
test('ops: late invalid receipt line produces zero receipt/evidence/journal writes',()=>{const f=fixture(),r=receive();r.payload.lines[2].order_line_id='FOREIGN';r.payload.delivery_note_file_id='note-file';noWrite(f,()=>f.api('store').command(r),/linkage/);});
test('ops: multi-line goods-in, quarantine, discrepancy tasks, full payload replay, order concurrency',()=>{const f=fixture(),r=receive();const res=f.api('store').command(r).result;assert.equal(res.receipt_lines.length,3);assert.equal(f.s.get('Deliveries','DEL').received_by,'store');assert.equal(f.s.get('Orders','ORDER').version,2);assert.ok(res.stock_movements.some(m=>m.to==='LOC-quarantine'));const state=snapshot(f);assert.equal(f.api('store').command(r).result.replay,true);assert.equal(snapshot(f),state);noWrite(f,()=>f.api('store').command({...r,payload:{...r.payload,discrepancy_note:'changed'}}),/CONFLICT/);});
for(const kind of ['duplicate','infinite','negative','over','stale','wrong-job','role'])test('ops receipt refuses '+kind,()=>{const f=fixture(),r=receive();let actor='store',re=/QUANTITY|quantity|DUPLICATE|STALE|MISMATCH|ROLE/;if(kind==='duplicate')r.payload.lines.push(r.payload.lines[0]);if(kind==='infinite')r.payload.lines[0].quantity_good=Infinity;if(kind==='negative')r.payload.lines[0].quantity_good=-1;if(kind==='over')r.payload.lines[0].quantity_good=20;if(kind==='stale')r.expected_version=5;if(kind==='wrong-job')r.job_id='J';if(kind==='role')actor='installer';noWrite(f,()=>f.api(actor).command(r),re);});
test('ops: quarantine is role protected, version and balance checked, audited and idempotent',()=>{const f=fixture(),r=quarantine();noWrite(f,()=>f.api('office').command(r),/ROLE/);const res=f.api('store').command(r).result;assert.equal(res.store_balance,18);assert.equal(f.api('store').command(r).result.replay,true);assert.equal(f.s.list('StockMovements').length,2);noWrite(f,()=>f.api('store').command({...r,command_id:'Q2',expected_version:2}),/stock balance/);});
test('ops: incomplete flush is RecoveryRequired and cannot be replayed',()=>{const f=fixture(),original=f.s.insert;f.s.insert=function(n,r){if(n==='AuditEvents')throw Error('simulated write failure');return original.call(this,n,r);};assert.throws(()=>f.api().command(cmd('IW_START')),/write failure/);assert.equal(f.s.get('CommitJournal','CJ-R1C-CMD-IW_START').state,'RecoveryRequired');assert.throws(()=>f.api().command(cmd('IW_START')),/RECOVERY_REQUIRED/);});
test('ops: focused reads expose authoritative versions, never another installer or finance',()=>{const f=fixture();const r=f.api().read({read_type:'INSTALLER_WORKFLOW',work_package_id:'WP'});assert.equal(r.data.expected_version,1);assert.equal(r.data.questions.length,0);assert.ok(!JSON.stringify(r).includes('gross_pence'));noWrite(f,()=>f.api('other').read({read_type:'INSTALLER_WORKFLOW',work_package_id:'WP'}),/ASSIGNMENT/);const g=f.api('store').read({read_type:'GOODS_IN_DETAIL',payload:{delivery_id:'DEL'}});assert.equal(g.data.lines.length,3);assert.equal(g.data.expected_version,1);const b=f.api('store').read({read_type:'STOCK_BALANCE',payload:{product_id:'PROD-P460'}});assert.equal(b.data.store_balance,20);});
test('ops: parent/child ready barrier, deterministic arbitrary lines, no editable received_by',()=>{const c=requestContext(),parent={id:'P',command_id:'RCPT',job_id:'JM',delivery_id:'DEL',expected_version:1,submitted_by:'store@test.invalid',status:'Ready',line_count:30,delivery_note_reference:'REF',received_by:'admin'},lines=Array.from({length:30},(_,i)=>({id:'L'+i,request_id:'P',order_line_id:'OL'+i,quantity_good:1}));const a=c._r1cBuildRequest('GOODS_IN_RECEIVE',parent,lines,'store@test.invalid',()=>{}),b=c._r1cBuildRequest('GOODS_IN_RECEIVE',parent,lines.slice().reverse(),'store@test.invalid',()=>{});assert.equal(JSON.stringify(a),JSON.stringify(b));assert.equal(a.payload.lines.length,30);assert.equal(a.payload.received_by,undefined);assert.throws(()=>c._r1cBuildRequest('GOODS_IN_RECEIVE',parent,lines.slice(1),'store@test.invalid',()=>{}),/NOT_SYNCED/);assert.throws(()=>c._r1cBuildRequest('GOODS_IN_RECEIVE',{...parent,status:'Draft'},lines,'store@test.invalid',()=>{}),/NOT_READY/);});
function cloudFixture(kind){
  const f=fixture(),c=vm.createContext({console:{log(){}},Intl,Date,JSON,Number,Object,Array,String,Math,RegExp,Error});
  if(kind==='bound')for(const file of ['apps-script/s17/S17Admin.js','apps-script/installer/InstallerWorkflow.js','apps-script/materials/MaterialsWorkflow.js','apps-script/r1-appsheet/R1AppSheetAdapter.js'])vm.runInContext(fs.readFileSync(file,'utf8'),c,{filename:file});
  else vm.runInContext(fs.readFileSync('standalone-bridge/AppSheetBridge.js','utf8'),c);
  const grids=Object.fromEntries(schema.tables.map(t=>{const h=t.columns.map(c=>c.name);return[t.name,[h,...f.s.list(t.name).map(r=>h.map(k=>r[k]??''))]];}));
  let actor='installer',config={environment:'DEV',sheetId:core.R1A_BOUND_DEV_SHEET_ID,evidenceFolderId:'DEV-UPLOADS'},held=false;
  const sheets={};
  function sheet(n){return sheets[n]||(sheets[n]={getName:()=>n,getLastColumn:()=>grids[n][0]?.length||0,getLastRow:()=>grids[n].length,getMaxRows:()=>1000,getMaxColumns:()=>100,insertColumnsAfter(){},getRange(row,col,height=1,width=1){return{getValues(){return Array.from({length:height},(_,i)=>Array.from({length:width},(_,j)=>grids[n][row+i-1]?.[col+j-1]??''));},setValues(values){values.forEach((r,i)=>r.forEach((v,j)=>{grids[n][row+i-1]??=[];grids[n][row+i-1][col+j-1]=typeof v==='string'&&v.startsWith("'")?v.slice(1):v;}));},setNumberFormat(){}};}});}
  const ss={getId:()=>core.R1A_BOUND_DEV_SHEET_ID,getSheets:()=>Object.keys(grids).map(sheet),insertSheet(n){assert.ok(!grids[n]);grids[n]=[];return sheet(n);}};
  c.SpreadsheetApp={openById:id=>{assert.equal(id,core.R1A_BOUND_DEV_SHEET_ID);return ss;},getActiveSpreadsheet:()=>ss,flush(){}};
  c.PropertiesService={getScriptProperties:()=>({getProperty:()=>JSON.stringify(config)})};
  c.Session={getActiveUser:()=>({getEmail:()=>actor?actor+'@test.invalid':''}),getEffectiveUser:()=>({getEmail:()=> 'owner@test.invalid'})};
  c.LockService={getScriptLock:()=>({waitLock(){assert.equal(held,false);held=true;},releaseLock(){assert.equal(held,true);held=false;}})};
  for(const service of ['CalendarApp','UrlFetchApp','MailApp','GmailApp','DriveApp'])c[service]=new Proxy({},{get(){throw Error('EXTERNAL FORBIDDEN '+service);}});
  function add(n,r){if(!grids[n])grids[n]=[Array.from(c.R1C_REQUEST_HEADERS[n])];grids[n].push(grids[n][0].map(k=>r[k]??''));}
  return{c,grids,ss,add,setActor:x=>actor=x,setConfig:x=>config=x};
}
for(const kind of ['bound','standalone'])test('generated '+kind+': real request-row -> authenticated backend -> version/audit/replay with strict headers',()=>{
  const f=cloudFixture(kind);f.add('DEVInstallerCommandRequests',installerRow());
  let r=JSON.parse(f.c.appSheetR1CommandFromRequestRow('IW_START','REQ','installer@test.invalid'));assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.result.status,'InProgress');
  const before=JSON.stringify(f.grids);r=JSON.parse(f.c.appSheetR1CommandFromRequestRow('IW_START','REQ','installer@test.invalid'));assert.equal(r.result.replay,true);assert.equal(JSON.stringify(f.grids),before);
  f.setConfig({environment:'PROD',sheetId:core.R1A_BOUND_DEV_SHEET_ID});r=JSON.parse(f.c.appSheetR1CommandFromRequestRow('IW_START','REQ','installer@test.invalid'));assert.equal(r.ok,false);assert.match(r.error,/DEV_ONLY/);
});
for(const kind of ['bound','standalone'])test('generated '+kind+': goods-in child rows dispatch existing materials workflow',()=>{
  const f=cloudFixture(kind);f.setActor('store');f.add('DEVGoodsInRequests',{id:'R',command_id:'RECEIPT',job_id:'JM',delivery_id:'DEL',expected_version:1,submitted_by:'store@test.invalid',status:'Ready',line_count:3,delivery_note_reference:'DN'});
  for(let i=1;i<=3;i++)f.add('DEVGoodsInRequestLines',{id:'L'+i,request_id:'R',order_line_id:'LINE'+i,quantity_good:9,quantity_damaged:1,quantity_short:0});
  const r=JSON.parse(f.c.appSheetR1CommandFromRequestRow('GOODS_IN_RECEIVE','R','store@test.invalid'));assert.equal(r.ok,true,JSON.stringify(r));assert.equal(r.result.receipt_lines.length,3);assert.equal(r.result.complete,true);
});
test('generated: provision only four request tables, check is read-only, apply is additive and repeatable',()=>{
  const f=cloudFixture('standalone');f.setActor('admin');const before=JSON.stringify(f.grids);const check=f.c.runR1CRequestProvisionCheck();assert.equal(check.tables.length,4);assert.equal(JSON.stringify(f.grids),before);
  f.c.runR1CProvisionRequestTables();const after=JSON.stringify(f.grids);f.c.runR1CProvisionRequestTables();assert.equal(JSON.stringify(f.grids),after);assert.deepEqual(Object.keys(f.grids).filter(n=>n.startsWith('DEV')).sort(),['DEVGoodsInRequestLines','DEVGoodsInRequests','DEVInstallerCommandRequests','DEVStockCommandRequests']);
  assert.equal(f.c.runR1CRequestProvisionCheck().tables.every(t=>t.missing_columns.length===0),true);
  f.setActor('installer');assert.throws(()=>f.c.runR1CProvisionRequestTables(),/ROLE/);
});
test('generated: useremail-only path works with blank active session; row submitter and session mismatch still refused',()=>{
  const f=cloudFixture('standalone');f.add('DEVInstallerCommandRequests',installerRow());f.setActor('');let r=JSON.parse(f.c.appSheetR1CommandFromRequestRow('IW_START','REQ','installer@test.invalid'));assert.equal(r.ok,true,JSON.stringify(r));r=JSON.parse(f.c.appSheetR1CommandFromRequestRow('IW_START','REQ',''));assert.equal(r.ok,false);assert.match(r.error,/AUTHENTICATED/);r=JSON.parse(f.c.appSheetR1CommandFromRequestRow('IW_START','REQ','admin@test.invalid'));assert.match(r.error,/ACTOR_MISMATCH/);
});
test('generated: AppSheet upload resolves only in DEV root, missing/ambiguous/path traversal safely refused',()=>{
  const f=cloudFixture('standalone');let reads=0;
  const iter=values=>{let i=0;return{hasNext:()=>i<values.length,next:()=>values[i++]};};
  const file={getId:()=> 'FILE',getName:()=> 'image.jpg',getMimeType:()=> 'image/jpeg',isTrashed:()=>false};
  f.c.DriveApp={getFolderById(id){assert.equal(id,'DEV-UPLOADS');reads++;return{getFoldersByName:name=>iter(name==='uploads'?[{getFilesByName:name=>iter(name==='image.jpg'?[file]:[])}]:[]),getFilesByName:()=>iter([file,file])};}};
  const resolved=f.c._r1cResolveUpload('uploads/image.jpg');assert.equal(resolved.drive_file_id,'FILE');assert.equal(reads,1);
  for(const path of ['../secret','/root/file','https://drive.google.com/file','uploads/%2e%2e/file','uploads\\file'])assert.throws(()=>f.c._r1cResolveUpload(path),/PATH_INVALID/);
  assert.equal(reads,1);assert.throws(()=>f.c._r1cResolveUpload('uploads/pending.jpg'),/UPLOAD_PENDING/);assert.throws(()=>f.c._r1cResolveUpload('image.jpg'),/AMBIGUOUS/);
});
test('generated: no assignment => no Drive metadata lookup and no writes',()=>{const f=cloudFixture('standalone');f.setActor('other');f.add('DEVInstallerCommandRequests',installerRow({submitted_by:'other@test.invalid',command_type:'IW_PROGRESS',evidence_path:'uploads/image.jpg'}));const before=JSON.stringify(f.grids);const r=JSON.parse(f.c.appSheetR1CommandFromRequestRow('IW_PROGRESS','REQ','other@test.invalid'));assert.match(r.error,/ASSIGNMENT/);assert.equal(JSON.stringify(f.grids),before);});
test('generated: all new cloud commands preserve dependencies and execute without module/import globals',()=>{
  for(const type of ['IW_PROGRESS','IW_REPORT_COMPLETION','IW_REPORT_PROBLEM','IW_REPORT_VARIATION','IW_COMMISSIONING_DRAFT','STOCK_QUARANTINE']){
    const f=cloudFixture('standalone');let r;
    if(type==='STOCK_QUARANTINE'){f.setActor('store');r=quarantine();}
    else{const payloads={IW_PROGRESS:{note:'Progress'},IW_REPORT_COMPLETION:{outcome:'Complete',actual_end:'2026-09-01'},IW_REPORT_PROBLEM:{category:'Access',description:'Locked gate'},IW_REPORT_VARIATION:{description:'Mesh'},IW_COMMISSIONING_DRAFT:{evidence:[{drive_file_id:'FILE'}]}};r=cmd(type,{payload:payloads[type]});}
    const result=JSON.parse(f.c.appSheetR1Command(JSON.stringify(r)));assert.equal(result.ok,true,type+': '+JSON.stringify(result));
  }
  const f=cloudFixture('standalone');let result=JSON.parse(f.c.appSheetR1Command(JSON.stringify(cmd('IW_COMMISSIONING_DRAFT',{payload:{evidence:[{drive_file_id:'FILE'}]}}))));const id=result.result.submission_id;
  result=JSON.parse(f.c.appSheetR1Command(JSON.stringify(cmd('IW_COMMISSIONING_SUBMIT',{payload:{submission_id:id}}))));assert.equal(result.ok,true,JSON.stringify(result));
  f.setActor('office');result=JSON.parse(f.c.appSheetR1Command(JSON.stringify(cmd('COMMISSIONING_REVIEW',{expected_version:2,payload:{submission_id:id,status:'Returned',review_notes:'Needs clearer photo'}}))));assert.equal(result.ok,true,JSON.stringify(result));
});
test('generated: source/generator rebuilds have no drift',()=>{
  const files=['apps-script/r1-appsheet/R1AppSheetAdapter.js','standalone-bridge/AppSheetBridge.js','apps-script/installer/InstallerWorkflow.js','apps-script/materials/MaterialsWorkflow.js'];const before=files.map(f=>fs.readFileSync(f,'utf8'));
  for(const build of ['build-r1-appsheet','build-standalone-bridge','build-installer','build-materials'])cp.execFileSync(process.execPath,['scripts/'+build+'.cjs']);
  files.forEach((f,i)=>assert.equal(fs.readFileSync(f,'utf8'),before[i],f+' drift'));
});
