const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const core=require('../r1-appsheet/adapter.js');
const copy=x=>structuredClone(x);
function fixture(email='tanya@example.test'){
 const tables={People:[{id:'P-tanya',email:'tanya@example.test',active:true},{id:'P-hannah',email:'hannah@example.test',active:true},{id:'P-ben',email:'ben@example.test',active:true},{id:'P-installer',email:'installer@example.test',active:true}],PersonRoles:[{person_id:'P-tanya',role:'Office',active:true},{person_id:'P-hannah',role:'Office',active:true},{person_id:'P-ben',role:'Admin',active:true},{person_id:'P-installer',role:'Installer',active:true}],Jobs:[{id:'J-1',pilot_job:true,release_scope:'R1',version:1,salesperson_id:null},{id:'J-2',pilot_job:true,release_scope:'R1',version:1,salesperson_id:null},{id:'J-N',pilot_job:false,release_scope:'R1',version:1}],Tasks:[{id:'T-1',job_id:'J-1',owner_id:'P-tanya',backup_id:null,version:2,status:'Open'},{id:'T-H',job_id:'J-2',owner_id:'P-hannah',backup_id:null,version:1,status:'Open'}],Issues:[],ReleaseModes:[{function_id:'FN-01',target_release:'R1',authorised_job_scope:'Pilot',mode:'Automated'}],AuditEvents:[]};
 const store={getSheetId:()=>core.R1A_DEV_SHEET_ID,getEnvironment:()=> 'DEV',list:n=>copy(tables[n]||[]),get:(n,id)=>copy((tables[n]||[]).find(x=>x.id===id)||null),insert:(n,r)=>(tables[n]||(tables[n]=[])).push(copy(r))};
 const reads={officeHome:()=>({overdue:copy(tables.Tasks),due_today:[],due_soon:[],booking_review:[],unresolved_issues:[],health_alerts:[]}),jobOverview:(s,id)=>({job_id:id}),operationalQueue:()=>({queue:'booking',count:2,tasks:copy(tables.Tasks)}),releaseModes:()=>copy(tables.ReleaseModes),systemStatus:()=>({ok:true}),auditHistory:(s,id)=>({job_id:id,events:copy(tables.AuditEvents)}),actionAvailability:(s,id)=>({job_id:id}),taskActionAvailability:(s,id)=>({task_id:id})};
 const options={store,config:{environment:'DEV',sheetId:core.R1A_DEV_SHEET_ID},actorEmail:()=>email,reads,services:{}};
 return{tables,store,options,adapter:()=>core._r1aCreate(options)};
}
const cmd=(extra={})=>({command_id:'C-1',command_type:'COMPLETE_TASK',task_id:'T-1',expected_version:2,payload:{completion_note:'done'},...extra});
test('unknown command refused',()=>assert.throws(()=>fixture().adapter().command(cmd({command_type:'NOPE'})),/R1A_UNKNOWN_COMMAND/));
test('unauthenticated command refused',()=>assert.throws(()=>fixture('').adapter().command(cmd()),/AUTHENTICATED_EMAIL_REQUIRED/));
test('unknown actor refused',()=>assert.throws(()=>fixture('nobody@example.test').adapter().command(cmd()),/UNKNOWN_OR_DUPLICATE_ACTOR/));
test('unauthorized role refused',()=>assert.throws(()=>fixture('installer@example.test').adapter().command(cmd()),/ROLE_DENIED/));
test('non-Pilot scope refused',()=>{const f=fixture();f.options.services.COMPLETE_TASK=()=>({});f.tables.Jobs[0].pilot_job=false;assert.throws(()=>f.adapter().command(cmd()),/OUTSIDE_PILOT/)});
test('wrong ReleaseMode refused',()=>{const f=fixture();f.options.services.COMPLETE_TASK=()=>({});f.tables.ReleaseModes[0].mode='Disabled';assert.throws(()=>f.adapter().command(cmd()),/MODE_DENIED/)});
test('stale revision refused',()=>{const f=fixture();f.options.services.COMPLETE_TASK=()=>({});assert.throws(()=>f.adapter().command(cmd({expected_version:1})),/STALE_VERSION/)});
test('successful command uses installed workflow service and preserves audit provenance',()=>{const f=fixture();let calls=0;f.options.services.COMPLETE_TASK=({request,actor,store})=>{calls++;store.insert('AuditEvents',{id:'A-1',entity_id:request.task_id,initiating_actor:actor.id});return{committed:true}};const r=f.adapter().command(cmd());assert.equal(calls,1);assert.equal(r.result.committed,true);assert.equal(f.tables.AuditEvents[0].initiating_actor,'P-tanya')});
test('direct arbitrary field updates impossible',()=>{const f=fixture();f.options.services.COMPLETE_TASK=()=>({});assert.throws(()=>f.adapter().command({...cmd(),table:'Jobs',changes:{workflow_stage:'Done'}}),/INVALID_FIELDS/)});
test('read adapters require authentication and role',()=>{assert.throws(()=>fixture('').adapter().read({read_type:'SYSTEM_STATUS'}),/AUTHENTICATED/);assert.throws(()=>fixture('installer@example.test').adapter().read({read_type:'SYSTEM_STATUS'}),/ROLE_DENIED/)});
test('Hannah cannot see unrelated jobs',()=>{const f=fixture('hannah@example.test');assert.throws(()=>f.adapter().read({read_type:'JOB_OVERVIEW',job_id:'J-1'}),/JOB_ACCESS_DENIED/);assert.equal(f.adapter().read({read_type:'JOB_OVERVIEW',job_id:'J-2'}).ok,true)});
test('Tanya receives assigned office access and filtered home',()=>{const f=fixture();const r=f.adapter().read({read_type:'OFFICE_HOME'});assert.deepEqual(r.data.overdue.map(x=>x.id),['T-1']);assert.equal(r.data.overdue_count,1)});
test('Ben management reads work',()=>{const f=fixture('ben@example.test');assert.equal(f.adapter().read({read_type:'RELEASE_MODE_STATUS'}).ok,true);assert.equal(f.adapter().read({read_type:'JOB_OVERVIEW',job_id:'J-2'}).ok,true)});
test('intake remains policy-blocked even if a service is installed',()=>{const f=fixture();f.options.services.SOLD_INTAKE=()=>({});assert.throws(()=>f.adapter().command({command_id:'C-I',command_type:'SOLD_INTAKE',payload:{}}),/INTAKE_POLICY_NOT_APPROVED/)});
test('unsupported fixture-scoped command fails closed',()=>assert.throws(()=>fixture().adapter().command(cmd()),/COMMAND_UNSUPPORTED/));
test('wrong environment and sheet refuse; no external API source',()=>{const f=fixture();f.options.config.environment='PROD';assert.throws(()=>f.adapter().read({read_type:'SYSTEM_STATUS'}),/DEV_ONLY/);const src=fs.readFileSync('r1-appsheet/adapter.js','utf8')+fs.readFileSync('r1-appsheet/cloud-adapter.js','utf8');assert.doesNotMatch(src,/UrlFetchApp|MailApp|GmailApp|CalendarApp|DriveApp/)});
test('generated Apps Script parses and exposes only narrow entry points',()=>{const src=fs.readFileSync('apps-script/r1-appsheet/R1AppSheetAdapter.js','utf8');new vm.Script(src);assert.match(src,/function appSheetR1Read/);assert.match(src,/function appSheetR1Command/);assert.doesNotMatch(src,/updateRow|genericUpdate|activateProduction/)});
