const{test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const p=require('../s11/planner.js');const fx=require('../s11/fixture.js');const clone=v=>JSON.parse(JSON.stringify(v));
function store(){const names=['Jobs','WorkPackages','Allocations','People','Holidays','Settings','CalendarLinks','Outbox','CommitJournal','AuditEvents'];const d=Object.fromEntries(names.map(n=>[n,[]]));d.ReleaseModes=[{id:'RM-FN01',function_id:'FN-01',mode:'Automated',authorised_job_scope:'Pilot',target_release:'R1'},{id:'RM-FN02',function_id:'FN-02',mode:'Automated',authorised_job_scope:'Pilot',target_release:'R2'}];return{getSheetId:()=>p.S11_DEV_SHEET_ID,getEnvironment:()=> 'DEV',list:n=>clone(d[n]||[]),get:(n,id)=>clone((d[n]||[]).find(x=>x.id===id)||null),insert(n,x){if(!d[n])d[n]=[];if(d[n].some(y=>y.id===x.id))throw Error('dup '+n);d[n].push(clone(x));},update(n,id,x){const r=(d[n]||[]).find(y=>y.id===id);if(!r)throw Error('missing '+n);Object.assign(r,clone(x));}}}
function plan(s,extra={}){return p.planWorkPackage({command_id:'PLAN-1',job_id:'J-s11-plan',work_package_id:'WP-s11-roof',person_id:'PERSON-s11-installer',role:'Lead',start_at:'2026-11-11',end_at:'2026-11-13',expected_version:1,actor:'PERSON-tanya',reason:'Synthetic plan',at:fx.NOW,...extra},s);}
test('S11 valid allocation uses WorkPackage.id and People.id',()=>{const s=store();fx.seed(s);const r=plan(s);assert.equal(r.status,'Planned');assert.equal(r.allocation.work_package_id,'WP-s11-roof');assert.equal(r.allocation.person_id,'PERSON-s11-installer');assert.equal(s.get('WorkPackages','WP-s11-roof').planned_start,'2026-11-11');assert.equal(r.calendar.payload.end_at,'2026-11-14');});
test('S11 planner returns multi-day allocation in three and six week views',()=>{const s=store();fx.seed(s);plan(s);assert.equal(p.buildPlanner(s,'2026-11-09',3).rows.length,1);assert.equal(p.buildPlanner(s,'2026-11-09',6).rows[0].end_at,'2026-11-13');});
test('S11 planning replay does not duplicate allocation or Calendar action',()=>{const s=store();fx.seed(s);plan(s);assert.equal(plan(s).status,'Replayed');assert.equal(s.list('Allocations').length,1);assert.equal(s.list('CalendarLinks').length,1);assert.equal(s.list('Outbox').length,1);});
test('S11 conflicting command identity fails closed',()=>{const s=store();fx.seed(s);plan(s);assert.throws(()=>plan(s,{start_at:'2026-11-12'}),/S11_REVIEW: conflicting command/);});
test('S11 inactive installer is rejected',()=>{const s=store();fx.seed(s);s.update('People','PERSON-s11-installer',{active:false});assert.equal(plan(s).status,'NeedsReview');assert.equal(s.list('Allocations').length,0);});
test('S11 unavailable installer is rejected',()=>{const s=store();fx.seed(s);s.update('People','PERSON-s11-installer',{available_to:'2026-11-10'});assert.equal(plan(s).reason,'INSTALLER_UNAVAILABLE');});
test('S11 missing capacity fails closed',()=>{const s=store();fx.seed(s);s.update('People','PERSON-s11-installer',{capacity_per_day:null});assert.equal(plan(s).reason,'CAPACITY_NOT_CONFIGURED');});
test('S11 capacity conflict returns NeedsReview',()=>{const s=store();fx.seed(s);s.insert('Allocations',{id:'BUSY',work_package_id:'OTHER',person_id:'PERSON-s11-installer',role:'Lead',start_at:'2026-11-11',end_at:'2026-11-11',active:true});assert.equal(plan(s).reason,'CAPACITY_CONFLICT');});
test('S11 configured holiday returns NeedsReview',()=>{const s=store();fx.seed(s);s.insert('Holidays',{id:'HOL',local_date:new Date('2026-11-11T12:00:00Z'),office_closed:true});assert.equal(plan(s).reason,'OFFICE_HOLIDAY');});
test('S11 move revises selected package and preserves audit history',()=>{const s=store();fx.seed(s);plan(s);const r=p.moveWorkPackage({command_id:'MOVE-1',job_id:'J-s11-plan',work_package_id:'WP-s11-roof',allocation_id:'ALLOC-S11-PLAN-1',start_at:'2026-11-16',end_at:'2026-11-18',expected_version:2,actor:'PERSON-tanya',reason:'Customer agreed move',at:fx.NOW},s);assert.equal(r.status,'Moved');assert.equal(s.get('WorkPackages','WP-s11-roof').revision,3);assert.equal(s.list('AuditEvents').length,3);assert.equal(s.list('Allocations').length,1);});
test('S11 stale move is refused',()=>{const s=store();fx.seed(s);plan(s);assert.throws(()=>p.moveWorkPackage({command_id:'MOVE-X',job_id:'J-s11-plan',work_package_id:'WP-s11-roof',allocation_id:'ALLOC-S11-PLAN-1',start_at:'2026-11-16',end_at:'2026-11-18',expected_version:1,actor:'PERSON-tanya',reason:'Move'},s),/S11_STALE/);});
test('S11 Calendar update preserves external event reference',()=>{const s=store();fx.seed(s);plan(s);s.update('CalendarLinks','CL-ALLOC-S11-PLAN-1',{external_event_id:'EVENT-EXISTING',event_uid:'UID-EXISTING',status:'Active'});p.moveWorkPackage({command_id:'MOVE-1',job_id:'J-s11-plan',work_package_id:'WP-s11-roof',allocation_id:'ALLOC-S11-PLAN-1',start_at:'2026-11-16',end_at:'2026-11-18',expected_version:2,actor:'PERSON-tanya',reason:'Move',at:fx.NOW},s);const l=s.get('CalendarLinks','CL-ALLOC-S11-PLAN-1');assert.equal(l.external_event_id,'EVENT-EXISTING');assert.equal(l.status,'UpdatePending');assert.equal(s.list('Outbox').at(-1).action_type,'CalendarUpdate');});
test('S11 replacement deactivates old allocation and links new allocation',()=>{const s=store();fx.seed(s);plan(s);s.insert('People',fx.person('PERSON-s11-new'));const r=p.changeInstaller({command_id:'REPLACE-1',job_id:'J-s11-plan',work_package_id:'WP-s11-roof',old_allocation_id:'ALLOC-S11-PLAN-1',person_id:'PERSON-s11-new',mode:'Replace',expected_version:2,actor:'PERSON-tanya',reason:'Installer unavailable',at:fx.NOW},s);assert.equal(r.status,'Replaced');assert.equal(s.get('Allocations','ALLOC-S11-PLAN-1').active,false);assert.equal(r.allocation.replaced_allocation_id,'ALLOC-S11-PLAN-1');assert.equal(s.get('CalendarLinks','CL-ALLOC-S11-PLAN-1').status,'Cancelled');assert.equal(s.list('Outbox').filter(o=>o.action_type==='CalendarCancel').length,1);});
test('S11 adding second installer retains original allocation',()=>{const s=store();fx.seed(s);plan(s);s.insert('People',fx.person('PERSON-s11-second'));const r=p.changeInstaller({command_id:'ADD-1',job_id:'J-s11-plan',work_package_id:'WP-s11-roof',old_allocation_id:'ALLOC-S11-PLAN-1',person_id:'PERSON-s11-second',mode:'Add',expected_version:2,actor:'PERSON-tanya',reason:'Second installer',at:fx.NOW},s);assert.equal(r.status,'Added');assert.equal(s.get('Allocations','ALLOC-S11-PLAN-1').active,true);assert.equal(r.allocation.role,'Second');});
test('S11 ReleaseMode and scope are enforced',()=>{for(const mutate of [s=>s.update('ReleaseModes','RM-FN02',{mode:'Disabled'}),s=>s.update('Jobs','J-s11-plan',{pilot_job:false}),s=>s.getEnvironment=()=> 'PROD']){const s=store();fx.seed(s);mutate(s);assert.throws(()=>plan(s),/S11_REFUSED/);}});
test('S11 Date objects and strings normalize identically; invalid dates fail clearly',()=>{for(const x of ['2026-11-11','2026-11-11T00:00:00Z',new Date('2026-11-11T12:00:00Z')])assert.equal(p.localDate(x),'2026-11-11');for(const x of [null,'bad',new Date(NaN)])assert.throws(()=>p.localDate(x),/S11_DATE_INVALID/);});
test('S11 unrelated rows untouched and no outbound API exists',()=>{const s=store();fx.seed(s);const before=JSON.stringify(s.get('People','PERSON-s11-installer'));plan(s);assert.equal(JSON.stringify(s.get('People','PERSON-s11-installer')),before);assert.equal(s.list('Outbox')[0].response_summary,'CAPTURE_ONLY: no Calendar API call');assert.equal(/CalendarApp|UrlFetchApp/.test(fs.readFileSync('s11/planner.js','utf8')),false);});
test('S11 Apps Script bundle parses without generic-global collisions',()=>{const ctx=vm.createContext({console,SpreadsheetApp:{},PropertiesService:{}}),prior=['DEV_SHEET_ID','localDate','assertScope','template','holidays','addWorkingDays'].map(n=>'const '+n+'=null;').join('\n');vm.runInContext(prior+'\n'+fs.readFileSync('apps-script/s11/S11Planner.js','utf8'),ctx);for(const n of ['restoreS11SafeState','runS11FixtureDryRun','runS11FixtureApply','runS11FixtureValidate','runS11EnableFunctionsForSyntheticTest','runS11HappyPathTest'])assert.equal(typeof ctx[n],'function');});
