/* GENERATED by node scripts/build-s04.cjs. Bridge only; no Sheet adapter. */
var S04Bridge = (function() {
const requestApi = (function() {
const DEV_SHEET_ID = '1z7PNZtDdC4Z5eLbmTuQdqp0QpJSmuEvx3QvN3VyNTsc';
const clone = value => JSON.parse(JSON.stringify(value));
function refuse(code) { const e = new Error(code); e.code = code; throw e; }
function canonical(value) {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return '[' + value.map(canonical).join(',') + ']';
  return '{' + Object.keys(value).sort().map(k => JSON.stringify(k) + ':' + canonical(value[k])).join(',') + '}';
}
function keys(value, allowed) {
  if (!value || typeof value !== 'object' || Array.isArray(value) ||
      Object.keys(value).some(k => !allowed.includes(k))) refuse('INVALID_FIELDS');
}
function commandRequest(input) {
  keys(input, ['command_id', 'action', 'task_id', 'expected_version', 'payload', 'payload_hash']);
  for (const name of ['command_id', 'task_id']) {
    if (typeof input[name] !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9_-]{0,119}$/.test(input[name])) refuse('INVALID_' + name.toUpperCase());
  }
  if (input.action !== 'COMPLETE_TASK') refuse('ACTION_DENIED');
  if (!Number.isSafeInteger(input.expected_version) || input.expected_version < 1 || input.expected_version >= Number.MAX_SAFE_INTEGER) refuse('INVALID_VERSION');
  keys(input.payload, ['completion_note']);
  if (typeof input.payload.completion_note !== 'string' || input.payload.completion_note.length > 2000) refuse('INVALID_PAYLOAD');
  return { command_id: input.command_id, action: input.action, task_id: input.task_id,
    expected_version: input.expected_version, payload: { completion_note: input.payload.completion_note } };
}

return { canonical, commandRequest, DEV_SHEET_ID };
})();
/* Separate Google web-app project: USER_ACCESSING, no Sheets permission.
 * User identity comes only from the accessing-user Google execution context. */
const { canonical, commandRequest, DEV_SHEET_ID } = requestApi;
function fail(code) { const e = new Error(code); e.code = code; throw e; }
function createBridge(services) {
  const props = services.PropertiesService.getScriptProperties();
  function context() {
    const c = JSON.parse(props.getProperty('S04_BRIDGE_CONFIG') || 'null');
    if (!c || c.environment !== 'DEV' || c.sheetId !== DEV_SHEET_ID ||
        c.bridgeProjectId !== services.ScriptApp.getScriptId() || !c.backendProjectId ||
        !/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(c.backendUrl)) fail('BRIDGE_DEV_CONFIG_REQUIRED');
    // Effective identity is used ONLY as a consistency check, never a fallback.
    const email = services.Session.getActiveUser().getEmail().trim().toLowerCase();
    const effective = services.Session.getEffectiveUser().getEmail().trim().toLowerCase();
    if (!email || email !== effective) fail('ACCESSING_GOOGLE_USER_REQUIRED');
    if (!Array.isArray(c.allowedUsers) || !c.allowedUsers.includes(email)) fail('BRIDGE_USER_DENIED');
    const secret = props.getProperty('S04_IDENTITY_SECRET');
    if (!secret || secret.length < 32) fail('BRIDGE_SECRET_REQUIRED');
    return { c, email, secret };
  }
  const hex = bytes => bytes.map(b => ('0' + ((b + 256) % 256).toString(16)).slice(-2)).join('');
  const u = services.Utilities;
  const hash = value => hex(u.computeDigest(u.DigestAlgorithm.SHA_256, value, u.Charset.UTF_8));
  const hmac = (value, secret) => hex(u.computeHmacSha256Signature(value, secret, u.Charset.UTF_8));
  const users = () => services.PropertiesService.getUserProperties();
  function begin(taskId, version) {
    const { email } = context();
    const lock = services.LockService.getUserLock();
    if (!lock.tryLock(5000)) fail('BRIDGE_BUSY');
    try {
      const old = JSON.parse(users().getProperty('S04_PENDING') || 'null');
      if (old && old.email === email && old.request_hash && !old.finished) {
        if (old.request.task_id !== taskId || old.request.expected_version !== Number(version)) fail('RESOLVE_PENDING_COMMAND_FIRST');
        // Refresh rotates the CSRF challenge but preserves an uncertain command.
        old.challenge = u.getUuid() + u.getUuid(); old.expires_at = Date.now() + 15 * 60000;
        users().setProperty('S04_PENDING', JSON.stringify(old));
        return { challenge: old.challenge, email, task_id: taskId, expected_version: Number(version), note: old.request.payload.completion_note, resumed: true };
      }
      const request = commandRequest({ command_id: 'CMD-' + u.getUuid(), action: 'COMPLETE_TASK', task_id: taskId,
        expected_version: Number(version), payload: { completion_note: '' } });
      const challenge = u.getUuid() + u.getUuid();
      users().setProperty('S04_PENDING', JSON.stringify({ challenge, email, request, expires_at: Date.now() + 15 * 60000 }));
      return { challenge, email, task_id: request.task_id, expected_version: request.expected_version, note: '', resumed: false };
    } finally { lock.releaseLock(); }
  }
  function submit(challenge, note) {
    let locked = false;
    const lock = services.LockService.getUserLock();
    try {
      const { c, email, secret } = context();
      if (!lock.tryLock(5000)) fail('BRIDGE_BUSY'); locked = true;
      const state = JSON.parse(users().getProperty('S04_PENDING') || 'null');
      if (!state || state.challenge !== challenge || state.email !== email || state.expires_at <= Date.now()) fail('CHALLENGE_EXPIRED_OR_WRONG_USER');
      const request = commandRequest({ ...state.request, payload: { completion_note: note } });
      const requestHash = hash(canonical(request));
      if (state.request_hash && state.request_hash !== requestHash) fail('CHALLENGE_ALREADY_BOUND');
      // Persist exact command before dispatch; uncertain delivery retries the same ID.
      state.request = request; state.request_hash = requestHash;
      users().setProperty('S04_PENDING', JSON.stringify(state));
      const now = Date.now();
      const proof = { version: 'S04-IDENTITY-2', purpose: 'S04_COMPLETE_TASK', subject: email, email,
        jti: u.getUuid(), audience: 'S04:' + c.backendProjectId + ':' + c.sheetId,
        issued_at: now, expires_at: now + 120000, request_hash: requestHash };
      proof.signature = hmac(canonical(proof), secret);
      const response = services.UrlFetchApp.fetch(c.backendUrl, {
        method: 'post', contentType: 'application/json', followRedirects: true, muteHttpExceptions: true,
        payload: JSON.stringify({ command: request, proof })
      });
      if (response.getResponseCode() !== 200) fail('BACKEND_UNCONFIRMED');
      const result = JSON.parse(response.getContentText());
      if (!result || !['Committed', 'Failed', 'Pending'].includes(result.status)) fail('BACKEND_UNCONFIRMED');
      if (result.status === 'Committed' && (result.command_id !== request.command_id || result.task_id !== request.task_id ||
          result.version !== request.expected_version + 1 || !result.commit_id || result.committed !== true)) fail('BACKEND_UNCONFIRMED');
      if (result.status === 'Committed') {
        state.finished = true;
        users().setProperty('S04_PENDING', JSON.stringify(state));
      }
      return result;
    } catch (e) {
      return { status: e.code === 'BACKEND_UNCONFIRMED' || !e.code ? 'Pending' : 'Failed', committed: false,
        error: e.code || 'DELIVERY_UNCERTAIN_RETRY_SAME_COMMAND' };
    } finally { if (locked) lock.releaseLock(); }
  }
  return { begin, submit };
}
return { createBridge };

})();
