/* Resilience review cloud adapter (header-checked store; Tasks/AuditEvents/Outbox writes only). */
function _rsCloudConfig() { var c = JSON.parse(PropertiesService.getScriptProperties().getProperty('S01_CONFIG') || 'null'); if (!c || c.environment !== 'DEV') throw new Error('RS_REFUSED: exact DEV environment required'); return c; }
function _rsCloudGuard() { var ss = SpreadsheetApp.getActiveSpreadsheet(); _rsCloudConfig(); if (ss.getId() !== RS_DEV_SHEET_ID) throw new Error('RS_REFUSED: exact DEV sheet/environment required'); return ss; }
function _rsSheet(ss, name) { var m = ss.getSheets().filter(function (s) { return s.getName() === name; }); if (m.length !== 1) throw new Error('RS_SCHEMA: missing/duplicate tab ' + name); var sh = m[0], h = RS_HEADERS[name]; if (!h || sh.getLastColumn() < h.length || JSON.stringify(sh.getRange(1, 1, 1, h.length).getValues()[0]) !== JSON.stringify(h)) throw new Error('RS_SCHEMA: header mismatch ' + name); return sh; }
function _rsCell(v) { return v === null || v === undefined ? '' : typeof v === 'string' && /^[=+@'\-]/.test(v) ? "'" + v : v; }
function _rsCloudStore() {
  var ss = _rsCloudGuard();
  function list(name) { var sh = _rsSheet(ss, name), h = RS_HEADERS[name]; if (sh.getLastRow() < 2) return []; return sh.getRange(2, 1, sh.getLastRow() - 1, h.length).getValues().map(function (row) { var x = {}; h.forEach(function (k, i) { x[k] = row[i] === '' ? null : row[i]; }); return x; }).filter(function (r) { return r.id; }); }
  return {
    getSheetId: function () { return ss.getId(); }, getEnvironment: function () { _rsCloudGuard(); return 'DEV'; }, list: list,
    get: function (name, id) { var rows = list(name).filter(function (r) { return r.id === id; }); if (rows.length > 1) throw new Error('RS_SCHEMA: duplicate ID ' + id); return rows[0] || null; },
    insert: function (name, row) { if (['Tasks', 'AuditEvents'].indexOf(name) === -1) throw new Error('RS_REFUSED: review service inserts only Tasks/AuditEvents'); var sh = _rsSheet(ss, name), h = RS_HEADERS[name]; if (list(name).some(function (r) { return r.id === row.id; })) throw new Error('RS_SCHEMA: duplicate insert ' + row.id); for (var k in row) if (row.hasOwnProperty(k) && h.indexOf(k) === -1) throw new Error('RS_SCHEMA: unknown field ' + name + '.' + k); sh.getRange(sh.getLastRow() + 1, 1, 1, h.length).setValues([h.map(function (k) { return _rsCell(row[k]); })]); SpreadsheetApp.flush(); },
    update: function (name, id, patch) { if (['Tasks', 'Outbox'].indexOf(name) === -1) throw new Error('RS_REFUSED: review service updates only Tasks/Outbox'); var sh = _rsSheet(ss, name), h = RS_HEADERS[name], values = sh.getRange(2, 1, Math.max(1, sh.getLastRow() - 1), h.length).getValues(), idx = []; values.forEach(function (r, i) { if (r[0] === id) idx.push(i); }); if (idx.length !== 1) throw new Error('RS_SCHEMA: update row ' + id); var row = values[idx[0]]; for (var k in patch) { if (!patch.hasOwnProperty(k)) continue; if (h.indexOf(k) === -1) throw new Error('RS_SCHEMA: unknown field ' + name + '.' + k); row[h.indexOf(k)] = patch[k]; } sh.getRange(idx[0] + 2, 1, 1, h.length).setValues([row.map(_rsCell)]); SpreadsheetApp.flush(); },
    withLock: function (fn) { var lock = LockService.getScriptLock(); if (!lock.tryLock(5000)) throw new Error('RS_BUSY'); try { return fn(); } finally { lock.releaseLock(); } }
  };
}
function _rsResult(name, fn) { try { var result = fn(); var r = { test: name, pass: result.pass === undefined ? result.ok !== false : result.pass, detail: result.detail || result }; console.log(JSON.stringify(r)); return r; } catch (e) { var f = { test: name, pass: false, detail: String(e.message || e) }; console.log(JSON.stringify(f)); return f; } }
function _rsActor() { try { var e = Session.getActiveUser().getEmail(); return e ? String(e) : 'DEV-apps-script'; } catch (x) { return 'DEV-apps-script'; } }
function _rsStamp() { return new Date().toISOString().replace(/[^0-9]/g, '').substring(0, 14); }
function runRsReviewQueue() { return _rsResult('RS review queue', function () { return Object.assign({ ok: true }, _rsReviewQueue(_rsCloudStore(), {})); }); }
/* Scheduler-safe (e.g. every 30 minutes): review tasks for uncertain items + failure alerts (one per component per day). Requires FN-14 Automated/Pilot. */
function runRsSweep() { return _rsResult('RS sweep', function () { var s = _rsCloudStore(); return s.withLock(function () { var a = _rsRaiseReviewTasks(s, { actor: _rsActor(), command_id: 'RS-SWEEP-' + _rsStamp() }); var b = _rsFailureAlerts(s, { actor: _rsActor(), command_id: 'RS-ALERTS-' + _rsStamp() }); return { ok: true, review_tasks: a, alerts: b }; }); }); }
function runRsResolveOutbox(outboxId, resolution, externalId, reason) { return _rsResult('RS resolve outbox', function () { var s = _rsCloudStore(); return s.withLock(function () { return Object.assign({ ok: true }, _rsResolveOutbox(s, { actor: _rsActor(), command_id: 'RS-RESOLVE-' + outboxId + '-' + _rsStamp(), outbox_id: outboxId, resolution: resolution, external_id: externalId || null, reason: reason || 'Manual review resolution' })); }); }); }
