/* Xero adapter cloud adapter. DISABLED by default: runXoDispatch builds nothing and sends nothing unless S01_CONFIG.xeroMode === 'LIVE',
 * FN-09 is Automated/Pilot/R4 AND an approved connector injects a transport (none exists in this repository). */
function _xoCloudConfig() { var c = JSON.parse(PropertiesService.getScriptProperties().getProperty('S01_CONFIG') || 'null'); if (!c || c.environment !== 'DEV') throw new Error('XO_REFUSED: exact DEV environment required'); return c; }
function _xoCloudGuard() { var ss = SpreadsheetApp.getActiveSpreadsheet(); _xoCloudConfig(); if (ss.getId() !== XO_DEV_SHEET_ID) throw new Error('XO_REFUSED: exact DEV sheet/environment required'); return ss; }
function _xoSheet(ss, name) { var m = ss.getSheets().filter(function (s) { return s.getName() === name; }); if (m.length !== 1) throw new Error('XO_SCHEMA: missing/duplicate tab ' + name); var sh = m[0], h = XO_HEADERS[name]; if (!h || sh.getLastColumn() < h.length || JSON.stringify(sh.getRange(1, 1, 1, h.length).getValues()[0]) !== JSON.stringify(h)) throw new Error('XO_SCHEMA: header mismatch ' + name); return sh; }
function _xoCell(v) { return v === null || v === undefined ? '' : typeof v === 'string' && /^[=+@'\-]/.test(v) ? "'" + v : v; }
function _xoCloudStore() {
  var ss = _xoCloudGuard();
  function list(name) { var sh = _xoSheet(ss, name), h = XO_HEADERS[name]; if (sh.getLastRow() < 2) return []; return sh.getRange(2, 1, sh.getLastRow() - 1, h.length).getValues().map(function (row) { var x = {}; h.forEach(function (k, i) { x[k] = row[i] === '' ? null : row[i]; }); return x; }).filter(function (r) { return r.id; }); }
  return {
    getSheetId: function () { return ss.getId(); }, getEnvironment: function () { _xoCloudGuard(); return 'DEV'; }, list: list,
    get: function (name, id) { var rows = list(name).filter(function (r) { return r.id === id; }); if (rows.length > 1) throw new Error('XO_SCHEMA: duplicate ID ' + id); return rows[0] || null; },
    insert: function (name, row) { if (['Payments', 'Tasks', 'AuditEvents'].indexOf(name) === -1) throw new Error('XO_REFUSED: Xero adapter inserts only Payments/Tasks/AuditEvents'); var sh = _xoSheet(ss, name), h = XO_HEADERS[name]; if (list(name).some(function (r) { return r.id === row.id; })) throw new Error('XO_SCHEMA: duplicate insert ' + row.id); for (var k in row) if (row.hasOwnProperty(k) && h.indexOf(k) === -1) throw new Error('XO_SCHEMA: unknown field ' + name + '.' + k); sh.getRange(sh.getLastRow() + 1, 1, 1, h.length).setValues([h.map(function (k) { return _xoCell(row[k]); })]); SpreadsheetApp.flush(); },
    update: function (name, id, patch) { if (['InvoiceStages', 'Outbox'].indexOf(name) === -1) throw new Error('XO_REFUSED: Xero adapter updates only InvoiceStages/Outbox'); var sh = _xoSheet(ss, name), h = XO_HEADERS[name], values = sh.getRange(2, 1, Math.max(1, sh.getLastRow() - 1), h.length).getValues(), idx = []; values.forEach(function (r, i) { if (r[0] === id) idx.push(i); }); if (idx.length !== 1) throw new Error('XO_SCHEMA: update row ' + id); var row = values[idx[0]]; for (var k in patch) { if (!patch.hasOwnProperty(k)) continue; if (h.indexOf(k) === -1) throw new Error('XO_SCHEMA: unknown field ' + name + '.' + k); row[h.indexOf(k)] = patch[k]; } sh.getRange(idx[0] + 2, 1, 1, h.length).setValues([row.map(_xoCell)]); SpreadsheetApp.flush(); },
    withLock: function (fn) { var lock = LockService.getScriptLock(); if (!lock.tryLock(5000)) throw new Error('XO_BUSY'); try { return fn(); } finally { lock.releaseLock(); } }
  };
}
function _xoResult(name, fn) { try { var result = fn(); var r = { test: name, pass: result.pass === undefined ? result.ok !== false : result.pass, detail: result.detail || result }; console.log(JSON.stringify(r)); return r; } catch (e) { var f = { test: name, pass: false, detail: String(e.message || e) }; console.log(JSON.stringify(f)); return f; } }
function _xoActor() { try { var e = Session.getActiveUser().getEmail(); return e ? String(e) : 'DEV-apps-script'; } catch (x) { return 'DEV-apps-script'; } }
function _xoStamp() { return new Date().toISOString().replace(/[^0-9]/g, '').substring(0, 14); }
function runXoRequests() { return _xoResult('XO requests', function () { return Object.assign({ ok: true }, _xoRequests(_xoCloudStore(), { config: _xoCloudConfig() })); }); }
/* No transport is available in this project: with xeroMode LIVE this still refuses ("no approved transport injected"). */
function runXoDispatch() { return _xoResult('XO dispatch', function () { var s = _xoCloudStore(); return s.withLock(function () { return Object.assign({ ok: true }, _xoDispatch(s, { actor: _xoActor(), command_id: 'XO-DISPATCH-' + _xoStamp(), config: _xoCloudConfig() })); }); }); }
function runXoInvoiceCallback(requestId, xeroInvoiceId, invoiceNumber, sourceStatus) { return _xoResult('XO invoice callback', function () { var s = _xoCloudStore(); return s.withLock(function () { return Object.assign({ ok: true }, _xoInvoiceCallback(s, { actor: _xoActor(), command_id: 'XO-CB-' + requestId + '-' + _xoStamp(), request_id: requestId, xero_invoice_id: xeroInvoiceId, invoice_number: invoiceNumber || null, source_status: sourceStatus || null })); }); }); }
function runXoPaymentCallback(xeroInvoiceId, xeroPaymentId, amountPence, paymentDate) { return _xoResult('XO payment callback', function () { var s = _xoCloudStore(); return s.withLock(function () { return Object.assign({ ok: true }, _xoPaymentCallback(s, { actor: _xoActor(), command_id: 'XO-PAY-' + xeroPaymentId + '-' + _xoStamp(), xero_invoice_id: xeroInvoiceId, xero_payment_id: xeroPaymentId, amount_pence: Number(amountPence), payment_date: paymentDate || null })); }); }); }
function runXoReviewCancelInvoice(stageId, reason) { return _xoResult('XO review/cancel invoice', function () { var s = _xoCloudStore(); return s.withLock(function () { return Object.assign({ ok: true }, _xoReviewCancelInvoice(s, { actor: _xoActor(), command_id: 'XO-RC-' + stageId + '-' + _xoStamp(), stage_id: stageId, reason: reason || 'Review requested' })); }); }); }
