'use strict';
const ops=require('./operations.js');
const NOW='2026-11-11T12:00:00.000Z';
function seed(store){
  const templates=[['INS01','Installer confirmation call','Install','Office'],['INS02','Missing commissioning reminder','Install','Installer'],['INS04','Customer call','Aftercare','Office'],['REM01','Agree return date with customer','Aftercare','Office'],['ISS01','Review variation','Aftercare','VariationApprover'],['ISS02','Investigate and resolve issue','Aftercare','Office'],['GHL01','Move GHL opportunity','Aftercare','Office']];
  for(const [code,title,group,role] of templates)if(!store.get('TaskTemplates','TPL-'+code))store.insert('TaskTemplates',{id:'TPL-'+code,template_code:code,title,group,default_owner_role:role,trigger_event:'S10 synthetic',due_rule:'Authoritative S10 rule',evidence_required:'Recorded outcome',active:true,template_version:'1.0',created_at:NOW,created_by:'S10',updated_at:NOW,updated_by:'S10',version:1,commit_id:'S10'});
  for(const p of [{id:'PERSON-tanya',role:'Office'},{id:'PERSON-hannah',role:'VariationApprover'},{id:'PERSON-installer-a',role:'Installer'}]){if(!store.get('People',p.id))store.insert('People',{id:p.id,email:'synthetic@dev.example.invalid',display_name:p.id,role:p.role,active:true,calendar_id:null,notification_email:null,capacity_per_day:null,available_from:null,available_to:null,backup_person_id:null,company_id:null,created_at:NOW,created_by:'S10',updated_at:NOW,updated_by:'S10',version:1,source_system:'S10',source_record_id:null,commit_id:'S10'});if(!store.get('PersonRoles','ROLE-'+p.id))store.insert('PersonRoles',{id:'ROLE-'+p.id,person_id:p.id,role:p.role,active:true,created_at:NOW,created_by:'S10',updated_at:NOW,updated_by:'S10',version:1,source_system:'S10',commit_id:'S10'});}
}
function job(id='J-s10-ready'){return{id,job_id:'SS-S10R-EADY',customer_id:'CUST-s10',display_name:'S10 DEV Synthetic',sold_submission_id:'S10-sold',booking_submission_id:'S10-booking',sold_at:'2026-10-01T00:00:00.000Z',salesperson_id:null,lead_source:'S10',quote_reference:'S10',presale_file_id:null,finance_route:'Standard',contract_status:'Signed',contract_id:'S10',contract_signed_at:'2026-10-01T00:00:00.000Z',contract_evidence_id:null,original_net_pence:100,current_vat_pence:null,original_vat_pence:0,original_gross_pence:100,approved_change_pence:null,current_contract_gross_pence:100,valuation_basis:'S10',sold_booking_match_status:'Match',customer_details_verified_at:'2026-10-01T00:00:00.000Z',customer_details_verified_by:'PERSON-tanya',deposit_bank_confirmed_at:'2026-10-01T00:00:00.000Z',deposit_bank_confirmed_by:'PERSON-tanya',deposit_bank_reference:'S10',roof_required:true,electrical_required:false,scaffold_required:false,workflow_stage:'Aftercare',booking_approved_at:'2026-10-01T00:00:00.000Z',booking_approved_by:'PERSON-tanya',operational_complete_at:null,operational_complete_by:null,customer_happy_at:'2026-11-09T10:00:00.000Z',customer_happy_by:'PERSON-tanya',handover_status:'NotReady',financial_status:'Pending',cancellation_at:null,cancellation_by:null,cancellation_reason:null,archived_at:null,next_action_at:null,account_policy_version:null,pilot_job:true,release_scope:'R1',created_at:NOW,created_by:'S10',updated_at:NOW,updated_by:'S10',version:1,source_system:'S10-fixture',source_record_id:null,commit_id:'S10'};}
function pkg(){return{id:'WP-s10-roof',job_id:'J-s10-ready',trade:'Roof',required:true,planned_start:'2026-11-05',planned_end:'2026-11-06',actual_start:'2026-11-05',actual_end:'2026-11-06',status:'ConfirmedComplete',need_by_date:null,completion_outcome:'Complete',installer_confirmation_at:'2026-11-09T10:00:00.000Z',installer_confirmation_by:'PERSON-tanya',commissioning_required:true,sequence:1,revision:1,parent_package_id:null,created_at:NOW,created_by:'S10',updated_at:NOW,updated_by:'S10',version:1,source_system:'S10',commit_id:'S10'};}
function installHappy(store){seed(store);if(!store.get('Jobs','J-s10-ready'))store.insert('Jobs',job());if(!store.get('WorkPackages','WP-s10-roof'))store.insert('WorkPackages',pkg());if(!store.get('Allocations','ALLOC-s10'))store.insert('Allocations',{id:'ALLOC-s10',work_package_id:'WP-s10-roof',person_id:'PERSON-installer-a',role:'Lead',start_at:'2026-11-05',end_at:'2026-11-06',active:true,replaced_allocation_id:null,cancellation_reason:null,calendar_link_id:null,created_at:NOW,created_by:'S10',updated_at:NOW,updated_by:'S10',version:1,source_system:'S10',commit_id:'S10'});if(!store.get('CommissioningSubmissions','CS-s10'))store.insert('CommissioningSubmissions',{id:'CS-s10',job_id:'J-s10-ready',work_package_id:'WP-s10-roof',allocation_id:'ALLOC-s10',installer_id:'PERSON-installer-a',template_version:'S10-sample',status:'Accepted',submitted_at:'2026-11-09T09:00:00.000Z',reviewed_at:'2026-11-09T10:00:00.000Z',reviewed_by:'PERSON-tanya',review_notes:'Synthetic accepted state only',supersedes_submission_id:null,created_at:NOW,created_by:'S10',updated_at:NOW,updated_by:'S10',version:1,commit_id:'S10'});}
module.exports={NOW,seed,job,pkg,installHappy};
