/* Build S05Core.gs from s05/mapping.js, booking-apply.js and intake.js. */
const fs = require('node:fs');

function buildS05Core() {
  const modules = ['s05/mapping.js', 's05/booking-apply.js', 's05/intake.js'];
  const names = { 's05/mapping.js': 'm0', 's05/booking-apply.js': 'mApply', 's05/intake.js': 'm1' };

  const sections = modules.map(file => {
    let code = fs.readFileSync(file, 'utf8');
    code = code.replace(/require\('\.\/mapping\.js'\)/g, names['s05/mapping.js']);
    code = code.replace(/require\('\.\/booking-apply\.js'\)/g, names['s05/booking-apply.js']);
    code = code.replace(/require\('\.\.\/config\/booking-product-map\.example\.json'\)/g,
      'JSON.parse(' + JSON.stringify(fs.readFileSync('config/booking-product-map.example.json', 'utf8')) + ')');
    code = code.replace(/require\('\.\.\/s06\/gates\.js'\)/g, 'null');
    code = code.replace(/\nmodule\.exports = \{[\s\S]*?\};/, '');
    code = code.replace(/\nif \(typeof module !== 'undefined'\)[\s\S]*$/, '');

    let exports;
    if (file === 's05/mapping.js') {
      exports = '{ buildFieldMap, extractField, applyMappings, buildSyntheticMapping, resolveBookingJob, generateJobId, generateInternalJobId, generateCustomerId }';
    } else if (file === 's05/booking-apply.js') {
      exports = '{ applyBookingStructured, resolveInstallerByName, compareCustomerField, moneyPence, loadProductMap, DEFAULT_PRODUCT_MAP }';
    } else {
      exports = '{ createIntakeProcessor, processSoldIntake, processBookingIntake, validateIntake, intakeHash, buildIntakeRecord, buildCustomer, buildJob, generateJobId, generateInternalJobId, guard, DEV_SHEET_ID }';
    }
    return '// Source: ' + file + '\nconst ' + names[file] + ' = (function() {\n' + code + '\nreturn ' + exports + ';\n})();';
  });

  return '/* GENERATED by node scripts/build-s05.cjs — do not edit. */\nvar S05Core = (function() {\n' + sections.join('\n') + '\nreturn { createIntakeProcessor: m1.createIntakeProcessor, validateIntake: m1.validateIntake, intakeHash: m1.intakeHash, buildIntakeRecord: m1.buildIntakeRecord, guard: m1.guard, DEV_SHEET_ID: m1.DEV_SHEET_ID, buildSyntheticMapping: m0.buildSyntheticMapping, applyMappings: m0.applyMappings, resolveBookingJob: m0.resolveBookingJob, generateJobId: m0.generateJobId, generateInternalJobId: m0.generateInternalJobId, generateCustomerId: m0.generateCustomerId, applyBookingStructured: mApply.applyBookingStructured };\n})();\n';
}

if (require.main === module) {
  fs.mkdirSync('apps-script/s05', { recursive: true });
  fs.writeFileSync('apps-script/s05/S05Core.gs', buildS05Core());
  console.log('Built apps-script/s05/S05Core.gs');
}

module.exports = { buildS05Core };
