const fs = require('node:fs'), schema = require('../schema/tables.json');
const names = schema.tables.map(t => t.name);
const headers = Object.fromEntries(names.map(n => [n, schema.tables.find(t => t.name === n).columns.map(c => c.name)]));
const files = ['s16/health.js', 's16/fixture.js', 's16/cloud-adapter.js'];
const text = '/* Generated by npm run build:s16. DEV synthetic only. */\nvar S16_HEADERS=' + JSON.stringify(headers) + ';\n' +
  files.map(f => fs.readFileSync(f, 'utf8').replace(/^if\(typeof module[^\n]+\n?/gm, '')).join('\n');
fs.mkdirSync('apps-script/s16', { recursive: true });
fs.writeFileSync('apps-script/s16/S16Health.js', text);
