const fs = require('node:fs'), schema = require('../schema/tables.json');
const names = schema.tables.map(t => t.name);
const headers = Object.fromEntries(names.map(n => [n, schema.tables.find(t => t.name === n).columns.map(c => c.name)]));
const files = ['s17/admin.js', 's17/fixture.js', 's17/cloud-adapter.js'];
const text = '/* Generated by npm run build:s17. DEV synthetic only. */\nvar S17_HEADERS=' + JSON.stringify(headers) + ';\n' +
  files.map(f => fs.readFileSync(f, 'utf8').replace(/^if\(typeof module[^\n]+\n?/gm, '')).join('\n');
fs.mkdirSync('apps-script/s17', { recursive: true });
fs.writeFileSync('apps-script/s17/S17Admin.js', text);
