const fs = require('node:fs'), schema = require('../schema/tables.json');
const headers = Object.fromEntries(schema.tables.map(t => [t.name, t.columns.map(c => c.name)]));
const files = ['backup/service.js', 'backup/cloud-adapter.js'];
const text = '/* Generated by npm run build:backup. DEV full-data Drive backups, verification and non-destructive restore rehearsal. */\nvar BK_HEADERS=' + JSON.stringify(headers) + ';\n' +
  files.map(f => fs.readFileSync(f, 'utf8').replace(/^'use strict';\n/m, '').replace(/^if \(typeof module !== 'undefined'\) \{[\s\S]*?\n\}\n?/m, '')).join('\n');
fs.mkdirSync('apps-script/backup', { recursive: true });
fs.writeFileSync('apps-script/backup/BackupService.js', text);
