const fs=require('node:fs'),schema=require('../schema/tables.json');
const core=fs.readFileSync('s11/planner.js','utf8').replace("'use strict';",'').replace(/module\.exports=[\s\S]*$/,'');
const names=['Tasks','Jobs','WorkPackages','Allocations','People','Holidays','Settings','CalendarLinks','Outbox','CommitJournal','AuditEvents','ReleaseModes'];
const headers=Object.fromEntries(names.map(n=>[n,schema.tables.find(t=>t.name===n).columns.map(c=>c.name)]));
const prefix=`/* S11 DEV planning/Calendar capture bundle. No Calendar API calls. */
var S11_HEADERS=${JSON.stringify(headers)};
function _s11Guard(){var ss=SpreadsheetApp.getActiveSpreadsheet();if(ss.getId()!=='1z7PNZtDdC4Z5eLbmTuQdqp0QpJSmuEvx3QvN3VyNTsc')throw new Error('S11_REFUSED: wrong sheet');var c=JSON.parse(PropertiesService.getScriptProperties().getProperty('S01_CONFIG')||'null');if(!c||c.environment!=='DEV')throw new Error('S11_REFUSED: DEV only');return ss;}
function _s11Sheet(ss,n){var a=ss.getSheets();for(var i=0;i<a.length;i++)if(a[i].getName()===n)return a[i];return null;}
function _s11Read(ss,n){var sh=_s11Sheet(ss,n),h=S11_HEADERS[n];if(!sh||sh.getLastRow()<2)return[];var v=sh.getRange(2,1,sh.getLastRow()-1,Math.min(sh.getLastColumn(),h.length)).getValues(),out=[];for(var r=0;r<v.length;r++){var x={};for(var c=0;c<h.length&&c<v[r].length;c++)x[h[c]]=v[r][c]===''?null:v[r][c];out.push(x);}return out;}
function _s11Insert(ss,n,x){var sh=_s11Sheet(ss,n),h=S11_HEADERS[n],row=sh.getLastRow()+1;if(!sh)throw new Error('S11_CONFIG: tab missing '+n);if(row>sh.getMaxRows())throw new Error('CAPACITY: '+n);sh.getRange(row,1,1,h.length).setValues([h.map(function(k){var v=x[k];return v===null||v===undefined?'':(typeof v==='string'&&/^[=']/.test(v)?"'"+v:v);})]);SpreadsheetApp.flush();}
function _s11Update(ss,n,id,p){var sh=_s11Sheet(ss,n),h=S11_HEADERS[n],rows=_s11Read(ss,n),ri=-1;for(var i=0;i<rows.length;i++)if(rows[i].id===id){ri=i+2;break;}if(ri<0)throw new Error('Row: '+n+' '+id);var v=sh.getRange(ri,1,1,h.length).getValues()[0];Object.keys(p).forEach(function(k){var j=h.indexOf(k);if(j>=0)v[j]=p[k]===null||p[k]===undefined?'':p[k];});sh.getRange(ri,1,1,h.length).setValues([v]);SpreadsheetApp.flush();}
function _s11Store(ss){return{getSheetId:function(){return ss.getId();},getEnvironment:function(){_s11Guard();return'DEV';},list:function(n){return _s11Read(ss,n);},get:function(n,id){return _s11Read(ss,n).filter(function(x){return x.id===id;})[0]||null;},insert:function(n,x){_s11Insert(ss,n,x);},update:function(n,id,p){_s11Update(ss,n,id,p);}};}
function _s11Result(name,pass,detail){var r={test:name,pass:pass,detail:detail};console.log(JSON.stringify(r,null,2));return r;}
function _s11Job(){return{id:'J-s11-plan',job_id:'SS-S11P-LANN',customer_id:'CUST-s11',display_name:'S11 DEV Synthetic',finance_route:'Standard',contract_status:'Signed',sold_booking_match_status:'Match',roof_required:true,electrical_required:false,scaffold_required:false,workflow_stage:'Booked',handover_status:'NotReady',financial_status:'Pending',pilot_job:true,release_scope:'R2',created_at:'2026-11-01T12:00:00.000Z',created_by:'S11',updated_at:'2026-11-01T12:00:00.000Z',updated_by:'S11',version:1,source_system:'S11-fixture',commit_id:'S11'};}
function _s11Package(){return{id:'WP-s11-roof',job_id:'J-s11-plan',trade:'Roof',required:true,status:'Unscheduled',commissioning_required:true,sequence:1,revision:1,created_at:'2026-11-01T12:00:00.000Z',created_by:'S11',updated_at:'2026-11-01T12:00:00.000Z',updated_by:'S11',version:1,source_system:'S11',commit_id:'S11'};}
function _s11Person(){return{id:'PERSON-s11-installer',email:'s11-installer@dev.example.invalid',display_name:'S11 DEV Installer',role:'Installer',active:true,calendar_id:'CAL-S11-CAPTURE',capacity_per_day:1,available_from:'2026-11-01',available_to:'2026-12-31',created_at:'2026-11-01T12:00:00.000Z',created_by:'S11',updated_at:'2026-11-01T12:00:00.000Z',updated_by:'S11',version:1,source_system:'S11-fixture',commit_id:'S11'};}
function runS11FixtureDryRun(){var s=_s11Store(_s11Guard()),a=s.list('ReleaseModes').filter(function(r){return r.function_id==='FN-01';}),b=s.list('ReleaseModes').filter(function(r){return r.function_id==='FN-02';});return _s11Result('S11 fixture dry run',a.length===1&&b.length===1,{fn01:a.length,fn02:b.length,existing_job:!!s.get('Jobs','J-s11-plan')});}
function runS11FixtureApply(){var s=_s11Store(_s11Guard());if(!s.get('Jobs','J-s11-plan'))s.insert('Jobs',_s11Job());if(!s.get('WorkPackages','WP-s11-roof'))s.insert('WorkPackages',_s11Package());if(!s.get('People','PERSON-s11-installer'))s.insert('People',_s11Person());return _s11Result('S11 fixture apply',true,'Synthetic R2 planning fixture present');}
function _s11Modes(enable){var s=_s11Store(_s11Guard()),ids=['FN-01','FN-02'];for(var i=0;i<ids.length;i++){var id=ids[i],release=id==='FN-01'?'R1':'R2',rows=s.list('ReleaseModes').filter(function(r){return r.function_id===id;});if(rows.length!==1)return _s11Result('S11 modes',false,id+' missing/duplicate');var r=rows[0];if(r.target_release!==release)return _s11Result('S11 modes',false,id+' target must be '+release);if(enable&&!(r.mode==='Disabled'&&r.authorised_job_scope==='None')&&!(r.mode==='Automated'&&r.authorised_job_scope==='Pilot'))return _s11Result('S11 modes',false,id+' unexpected state');s.update('ReleaseModes',r.id,{mode:enable?'Automated':'Disabled',authorised_job_scope:enable?'Pilot':'None',updated_at:new Date().toISOString(),updated_by:enable?'S11-enable':'S11-restore',version:Number(r.version||0)+1});}return _s11Result('S11 modes',true,enable?'Enabled controlled pilot':'Restored safe state');}
function runS11EnableFunctionsForSyntheticTest(){return _s11Modes(true);}function restoreS11SafeState(){return _s11Modes(false);}
function runS11FixtureValidate(){var s=_s11Store(_s11Guard());return _s11Result('S11 fixture validate',!!s.get('Jobs','J-s11-plan')&&!!s.get('WorkPackages','WP-s11-roof')&&!!s.get('People','PERSON-s11-installer'),{job:!!s.get('Jobs','J-s11-plan'),package:!!s.get('WorkPackages','WP-s11-roof'),installer:!!s.get('People','PERSON-s11-installer')});}
function runS11HappyPathTest(){try{var s=_s11Store(_s11Guard()),wp=s.get('WorkPackages','WP-s11-roof'),input={command_id:'S11-PLAN-CLOUD',job_id:'J-s11-plan',work_package_id:'WP-s11-roof',person_id:'PERSON-s11-installer',role:'Lead',start_at:'2026-11-11',end_at:'2026-11-13',expected_version:wp?Number(wp.version):1,actor:'PERSON-tanya',reason:'S11 DEV synthetic plan',at:'2026-11-02T12:00:00.000Z'},existing=s.get('Allocations','ALLOC-S11-S11-PLAN-CLOUD'),r;if(existing)r={status:'Replayed',allocation:existing};else r=_s11PlanWorkPackage(input,s);var allocations=s.list('Allocations').filter(function(a){return a.id==='ALLOC-S11-S11-PLAN-CLOUD';}),links=s.list('CalendarLinks').filter(function(c){return c.allocation_id==='ALLOC-S11-S11-PLAN-CLOUD';}),out=s.list('Outbox').filter(function(o){return o.correlation_id==='S11-PLAN-CLOUD';}),pass=allocations.length===1&&links.length===1&&out.length===1&&out[0].response_summary==='CAPTURE_ONLY: no Calendar API call';return _s11Result('S11 happy path',pass,{status:r.status,allocations:allocations.length,calendar_links:links.length,outbox:out.length,external_calls:0});}catch(e){return _s11Result('S11 happy path',false,String(e.message||e));}}
`;
fs.mkdirSync('apps-script/s11',{recursive:true});fs.writeFileSync('apps-script/s11/S11Planner.js',prefix+'\n'+core);
