/* Dependency-free scoped bundle: output has no require/module runtime dependency. */
const fs = require('node:fs');
const path = require('node:path');
const modules = [
  'processor/types.js', 'processor/journal.js', 'processor/tasks.js', 'processor/reconciler.js',
  's04/processor.js', 's04/identity.js', 's04/sheet-store.js', 's04/runtime.js'
];
function build() {
  const names = Object.fromEntries(modules.map((p, i) => [p, 'm' + i]));
  const sections = modules.map(file => {
    let code = fs.readFileSync(file, 'utf8').replace(/require\('([^']+)'\)/g, (_, relative) => {
      const target = path.posix.normalize(path.posix.join(path.posix.dirname(file), relative));
      if (!names[target]) throw new Error('Unbundled dependency: ' + target);
      return names[target];
    });
    code = code.replace(/if \(typeof module !== 'undefined'\) \{\s*module\.exports = ([\s\S]*?);\s*\}\s*$/, 'return $1;');
    code = code.replace(/module\.exports = ([\s\S]*?);\s*$/, 'return $1;');
    if (/\brequire\s*\(|module\.exports/.test(code)) throw new Error('Unsupported module pattern: ' + file);
    return '// Source: ' + file + '\nconst ' + names[file] + ' = (function() {\n' + code + '\n})();';
  });
  const schema = JSON.parse(fs.readFileSync('schema/tables.json', 'utf8'));
  const tables = ['People', 'PersonRoles', 'PermissionRules', 'ReleaseModes', 'Jobs', 'Tasks', 'TaskDependencies', 'TaskEvents', 'AuditEvents', 'CommitJournal'];
  return '/* GENERATED by node scripts/build-s04.cjs — do not edit. */\nvar S04 = (function() {\n' + sections.join('\n') +
    '\nconst schema = ' + JSON.stringify({ tables: schema.tables.filter(t => tables.includes(t.name)) }) + ';\n' +
    'return { createProcessor: m4.createProcessor, commandRequest: m4.commandRequest, canonical: m4.canonical, createSignedActorProvider: m5.createSignedActorProvider, createSheetStore: m6.createSheetStore, execute: function(services, command, proof) { return m7.execute(services, schema, command, proof); } };\n})();\n';
}
function buildBridge() {
  const processor = fs.readFileSync('s04/processor.js', 'utf8');
  const requestCode = processor.slice(processor.indexOf('const DEV_SHEET_ID'), processor.indexOf('function active('));
  const source = fs.readFileSync('s04/bridge.js', 'utf8')
    .replace("require('./processor.js')", 'requestApi')
    .replace('module.exports = { createBridge };', 'return { createBridge };');
  return '/* GENERATED by node scripts/build-s04.cjs. Bridge only; no Sheet adapter. */\n' +
    'var S04Bridge = (function() {\nconst requestApi = (function() {\n' + requestCode +
    '\nreturn { canonical, commandRequest, DEV_SHEET_ID };\n})();\n' + source + '\n})();\n';
}
if (require.main === module) {
  fs.writeFileSync('apps-script/s04/S04Core.gs', build());
  fs.writeFileSync('apps-script/s04-bridge/BridgeCore.gs', buildBridge());
}
module.exports = { build, buildBridge };
