const fs=require('node:fs'),schema=require('../schema/tables.json');
const names=['CommunicationJobs','ReceiptLines','Jobs','WorkPackages','Allocations','Materials','Reservations','Orders','OrderLines','ScaffoldBookings','StockMovements','InvoiceStages','Payments','CommissioningSubmissions','JobEquipment','Handover','Issues','Tasks','TaskTemplates','CalendarLinks','Communications','GHLTasks','JobCosts','Outbox','People','PersonRoles','ReleaseModes','CommitJournal','AuditEvents'];
const headers=Object.fromEntries(names.map(n=>[n,schema.tables.find(t=>t.name===n).columns.map(c=>c.name)]));
const files=['s15/cancellation.js','s15/fixture.js','s15/cloud-adapter.js'];
const text='/* Generated by npm run build:s15. DEV synthetic only. */\nvar S15_HEADERS='+JSON.stringify(headers)+';\n'+files.map(f=>fs.readFileSync(f,'utf8').replace(/^if\(typeof module[^\n]+\n?/gm,'')).join('\n');
fs.mkdirSync('apps-script/s15',{recursive:true});fs.writeFileSync('apps-script/s15/S15Cancellation.js',text);
