const fs=require('node:fs');
const schema=require('../schema/tables.json');
const core=fs.readFileSync('s10/operations.js','utf8').replace("'use strict';",'').replace(/module\.exports=[\s\S]*$/,'');
const names=['Jobs','Tasks','TaskTemplates','People','PersonRoles','ReleaseModes','WorkPackages','Allocations','Calls','Issues','IssueEvents','CommissioningSubmissions','GHLTasks','Holidays'];
const headers=Object.fromEntries(names.map(n=>[n,schema.tables.find(t=>t.name===n).columns.map(c=>c.name)]));
const prefix=`/* S10 DEV smoke bundle. No outbound calls; GHL is a durable human task only. */
var _S10H=${JSON.stringify(headers)};
function _s10Guard(){var ss=SpreadsheetApp.getActiveSpreadsheet();if(ss.getId()!=='1z7PNZtDdC4Z5eLbmTuQdqp0QpJSmuEvx3QvN3VyNTsc')throw new Error('S10_REFUSED: wrong sheet');var c=JSON.parse(PropertiesService.getScriptProperties().getProperty('S01_CONFIG')||'null');if(!c||c.environment!=='DEV')throw new Error('S10_REFUSED: DEV only');return ss;}
function _s10Sheet(ss,n){var a=ss.getSheets();for(var i=0;i<a.length;i++)if(a[i].getName()===n)return a[i];return null;}
function _s10Read(ss,n){var sh=_s10Sheet(ss,n),h=_S10H[n];if(!sh||sh.getLastRow()<2)return[];var v=sh.getRange(2,1,sh.getLastRow()-1,Math.min(sh.getLastColumn(),h.length)).getValues(),out=[];for(var r=0;r<v.length;r++){var x={};for(var c=0;c<h.length&&c<v[r].length;c++)x[h[c]]=v[r][c]===''?null:v[r][c];out.push(x);}return out;}
function _s10Insert(ss,n,x){var sh=_s10Sheet(ss,n),h=_S10H[n],row=sh.getLastRow()+1;if(row>sh.getMaxRows())throw new Error('CAPACITY: '+n);sh.getRange(row,1,1,h.length).setValues([h.map(function(k){var v=x[k];return v===null||v===undefined?'':(typeof v==='string'&&/^[=']/.test(v)?"'"+v:v);})]);SpreadsheetApp.flush();}
function _s10Update(ss,n,id,p){var sh=_s10Sheet(ss,n),h=_S10H[n],rows=_s10Read(ss,n),ri=-1;for(var i=0;i<rows.length;i++)if(rows[i].id===id){ri=i+2;break;}if(ri<0)throw new Error('Row: '+n+' '+id);var v=sh.getRange(ri,1,1,h.length).getValues()[0];Object.keys(p).forEach(function(k){var j=h.indexOf(k);if(j>=0)v[j]=p[k]===null||p[k]===undefined?'':p[k];});sh.getRange(ri,1,1,h.length).setValues([v]);SpreadsheetApp.flush();}
function _s10Store(ss){return{getSheetId:function(){return ss.getId();},getEnvironment:function(){_s10Guard();return'DEV';},list:function(n){return _s10Read(ss,n);},get:function(n,id){return _s10Read(ss,n).filter(function(x){return x.id===id;})[0]||null;},insert:function(n,x){_s10Insert(ss,n,x);},update:function(n,id,p){_s10Update(ss,n,id,p);}};}
function _s10Result(name,pass,detail){var r={test:name,pass:pass,detail:detail};console.log(JSON.stringify(r,null,2));return r;}
function _s10Fixture(s){var n='2026-11-11T12:00:00.000Z';function ins(t,x){if(!s.get(t,x.id))s.insert(t,x);}var t=[['INS04','Customer call','Aftercare','Office'],['ISS01','Review variation','Aftercare','VariationApprover'],['ISS02','Investigate and resolve issue','Aftercare','Office']];t.forEach(function(a){ins('TaskTemplates',{id:'TPL-S10-'+a[0],template_code:a[0],title:a[1]+' (DEV synthetic)',group:a[2],default_owner_role:a[3],trigger_event:'S10 DEV synthetic',due_rule:'Authoritative S10 rule',evidence_required:'Recorded outcome',active:true,template_version:'DEV-1.0',created_at:n,created_by:'S10',updated_at:n,updated_by:'S10',version:1,commit_id:'S10'});});ins('PersonRoles',{id:'ROLE-S10-hannah-variation',person_id:'PERSON-hannah',role:'VariationApprover',active:true,created_at:n,created_by:'S10',updated_at:n,updated_by:'S10',version:1,source_system:'S10',commit_id:'S10'});}
function _s10Job(){return{id:'J-s10-ready',job_id:'SS-S10R-EADY',customer_id:'CUST-s10',display_name:'S10 DEV Synthetic',sold_submission_id:'S10-sold',booking_submission_id:'S10-booking',sold_at:'2026-10-01T00:00:00.000Z',finance_route:'Standard',contract_status:'Signed',sold_booking_match_status:'Match',roof_required:true,electrical_required:false,scaffold_required:false,workflow_stage:'Aftercare',customer_happy_at:'2026-11-09T10:00:00.000Z',customer_happy_by:'PERSON-tanya',handover_status:'NotReady',financial_status:'Pending',pilot_job:true,release_scope:'R1',created_at:'2026-11-11T12:00:00.000Z',created_by:'S10',updated_at:'2026-11-11T12:00:00.000Z',updated_by:'S10',version:1,source_system:'S10-fixture',commit_id:'S10'};}
function _s10Package(){return{id:'WP-s10-roof',job_id:'J-s10-ready',trade:'Roof',required:true,planned_start:'2026-11-05',planned_end:'2026-11-06',actual_start:'2026-11-05',actual_end:'2026-11-06',status:'ReportedComplete',completion_outcome:'Complete',installer_confirmation_at:null,installer_confirmation_by:null,commissioning_required:true,sequence:1,revision:1,created_at:'2026-11-11T12:00:00.000Z',created_by:'S10',updated_at:'2026-11-11T12:00:00.000Z',updated_by:'S10',version:1,source_system:'S10',commit_id:'S10'};}
function runS10FixtureDryRun(){var s=_s10Store(_s10Guard()),ids=['FN-01','FN-11','FN-18','FN-19'];return _s10Result('S10 fixture dry run',ids.every(function(id){return s.list('ReleaseModes').filter(function(r){return r.function_id===id;}).length===1;}),{functions:ids,jobs:s.list('Jobs').filter(function(j){return j.id==='J-s10-ready';}).length});}
function runS10FixtureApply(){var s=_s10Store(_s10Guard());_s10Fixture(s);if(!s.get('Jobs','J-s10-ready'))s.insert('Jobs',_s10Job());if(!s.get('WorkPackages','WP-s10-roof'))s.insert('WorkPackages',_s10Package());if(!s.get('Allocations','ALLOC-s10'))s.insert('Allocations',{id:'ALLOC-s10',work_package_id:'WP-s10-roof',person_id:'PERSON-installer-a',role:'Lead',active:true,created_at:'2026-11-11T12:00:00.000Z',created_by:'S10',updated_at:'2026-11-11T12:00:00.000Z',updated_by:'S10',version:1,source_system:'S10',commit_id:'S10'});if(!s.get('CommissioningSubmissions','CS-s10'))s.insert('CommissioningSubmissions',{id:'CS-s10',job_id:'J-s10-ready',work_package_id:'WP-s10-roof',allocation_id:'ALLOC-s10',installer_id:'PERSON-installer-a',template_version:'S10-sample',status:'Accepted',submitted_at:'2026-11-09T09:00:00.000Z',reviewed_at:'2026-11-09T10:00:00.000Z',reviewed_by:'PERSON-tanya',review_notes:'Synthetic accepted state only',created_at:'2026-11-11T12:00:00.000Z',created_by:'S10',updated_at:'2026-11-11T12:00:00.000Z',updated_by:'S10',version:1,commit_id:'S10'});return _s10Result('S10 fixture apply',true,'Synthetic fixtures present');}
function _s10Modes(enable){var s=_s10Store(_s10Guard()),want={'FN-01':enable?'Automated':'Disabled','FN-11':enable?'Manual':'Disabled','FN-18':enable?'Manual':'Disabled','FN-19':enable?'Manual':'Disabled'};for(var id in want){var rows=s.list('ReleaseModes').filter(function(r){return r.function_id===id;});if(rows.length!==1)return _s10Result('S10 modes',false,id+' missing/duplicate');var r=rows[0];if(r.target_release!=='R1')return _s10Result('S10 modes',false,id+' target must be R1');if(enable&&!(r.mode==='Disabled'&&r.authorised_job_scope==='None')&&!(r.mode===want[id]&&r.authorised_job_scope==='Pilot'))return _s10Result('S10 modes',false,id+' unexpected state');s.update('ReleaseModes',r.id,{mode:want[id],authorised_job_scope:enable?'Pilot':'None',updated_at:new Date().toISOString(),updated_by:enable?'S10-enable':'S10-restore',version:Number(r.version||0)+1});}return _s10Result('S10 modes',true,enable?'Enabled controlled Pilot/R1':'Restored Disabled/None/R1');}
function runS10EnableFunctionsForSyntheticTest(){return _s10Modes(true);}function restoreS10SafeState(){return _s10Modes(false);}
function runS10FixtureValidate(){var s=_s10Store(_s10Guard()),m={};['FN-01','FN-11','FN-18','FN-19'].forEach(function(id){m[id]=(s.list('ReleaseModes').filter(function(r){return r.function_id===id;})[0]||{}).mode||'missing';});return _s10Result('S10 fixture validate',!!s.get('Jobs','J-s10-ready'),m);}
function runS10HappyPathTest(){try{var s=_s10Store(_s10Guard()),j=s.get('Jobs','J-s10-ready'),testNow='2026-11-12T12:00:00.000Z';if(!j)return _s10Result('S10 happy path',false,'Run fixture apply');var wp=s.get('WorkPackages','WP-s10-roof'),callTasks=s.list('Tasks').filter(function(t){return t.job_id===j.id&&t.template_code==='INS01';});if(!wp)return _s10Result('S10 happy path',false,'Synthetic work package missing');if(!callTasks.length){if(wp.status==='ConfirmedComplete')callTasks=[_s10InsertTask(s,'INS01',j.id,'WorkPackages',wp.id,'R'+wp.revision,_s10AddStaffedDays(wp.actual_end||wp.planned_end,1,_s10Holidays(s)),_s10OwnerForRole(s,'Office')).task];else callTasks=_s10ScheduleInstallerCalls(j.id,s).created;}if(callTasks.length!==1)throw new Error('Expected one INS01 task');var callInput={id:'CALL-s10-roof-confirm',job_id:j.id,work_package_id:wp.id,task_id:callTasks[0].id,type:'Installer',person_id:'PERSON-installer-a',attempted_at:testNow,attempted_by:'PERSON-tanya',outcome:'Complete',notes:'DEV synthetic confirmation',actual_completion_confirmed:true,commit_id:'S10-CALL'},callResult=_s10RecordCall(callInput,s);if(!callResult.created){var savedCall=callResult.call,currentTask=s.get('Tasks',callTasks[0].id),currentPackage=s.get('WorkPackages',wp.id);if(currentTask.status!=='Complete')s.update('Tasks',currentTask.id,{status:'Complete',completed_at:savedCall.attempted_at,completed_by:savedCall.attempted_by,completion_note:savedCall.outcome,updated_at:testNow,updated_by:'S10-reconcile',version:Number(currentTask.version||0)+1});if(currentPackage.status!=='ConfirmedComplete'||!currentPackage.installer_confirmation_at)s.update('WorkPackages',currentPackage.id,{status:'ConfirmedComplete',installer_confirmation_at:savedCall.attempted_at,installer_confirmation_by:savedCall.attempted_by,updated_at:testNow,updated_by:'S10-reconcile',version:Number(currentPackage.version||0)+1});}var r=_s10ApproveOperationalCompletion(j.id,'PERSON-tanya',s,testNow),tasks=s.list('Tasks').filter(function(t){return t.job_id===j.id&&t.template_code==='GHL01';}),ghl=s.list('GHLTasks').filter(function(g){return g.job_id===j.id;}),calls=s.list('Calls').filter(function(c){return c.job_id===j.id;}),issues=s.list('Issues').filter(function(i){return i.job_id===j.id&&!S10_TERMINAL_ISSUES.has(i.status);});return _s10Result('S10 happy path',(['Completed','AlreadyComplete'].indexOf(r.status)>=0&&callTasks.length===1&&calls.length===1&&issues.length===0&&tasks.length===1&&ghl.length===1),{status:r.status,installer_calls:calls.length,open_issues:issues.length,ghl_tasks:tasks.length,ghl_records:ghl.length,outbound_calls:0,test_time:testNow});}catch(e){return _s10Result('S10 happy path',false,String(e.message||e));}}
`;
fs.mkdirSync('apps-script/s10',{recursive:true});fs.writeFileSync('apps-script/s10/S10Operations.js',prefix+'\n'+core);
