const fs=require('node:fs');
const files=['s20/release.js','s20/cloud-adapter.js'];
const text='/* Generated by npm run build:s20. DEV simulation only; no PROD execution. */\n'+files.map(f=>fs.readFileSync(f,'utf8').replace(/^if \(typeof module[^\n]+\n?/gm,'')).join('\n');
fs.mkdirSync('apps-script/s20',{recursive:true});
fs.writeFileSync('apps-script/s20/S20Release.js',text);
