/* S14 DEV accounting/reporting smoke bundle. No real API calls. */
var S14_HEADERS={"InvoiceStages":["id","job_id","stage","amount_net_pence","vat_pence","gross_pence","due_date","status","xero_invoice_id","invoice_number","xero_contact_id","reference","request_id","last_synced_at","source_status","sent_at","cancelled_at","created_at","created_by","updated_at","updated_by","version","source_system","commit_id"],"Payments":["id","invoice_stage_id","xero_payment_id","amount_pence","payment_date","status","reconciliation_evidence","last_synced_at","created_at","commit_id"],"Jobs":["id","job_id","customer_id","display_name","sold_submission_id","booking_submission_id","sold_at","salesperson_id","lead_source","quote_reference","presale_file_id","finance_route","contract_status","contract_id","contract_signed_at","contract_evidence_id","original_net_pence","original_vat_pence","original_gross_pence","approved_change_pence","current_contract_gross_pence","valuation_basis","sold_booking_match_status","customer_details_verified_at","customer_details_verified_by","deposit_bank_confirmed_at","deposit_bank_confirmed_by","deposit_bank_reference","roof_required","electrical_required","scaffold_required","workflow_stage","booking_approved_at","booking_approved_by","operational_complete_at","operational_complete_by","customer_happy_at","customer_happy_by","handover_status","financial_status","cancellation_at","cancellation_by","cancellation_reason","archived_at","next_action_at","account_policy_version","pilot_job","release_scope","created_at","created_by","updated_at","updated_by","version","source_system","source_record_id","commit_id"],"JobCosts":["id","job_id","category","supplier_id","source_document_id","amount_net_pence","vat_pence","status","accounting_date","policy_version","created_at","created_by","updated_at","updated_by","version","commit_id"],"ReportSnapshots":["id","period_start","period_end","as_of_at","policy_version","report_type","totals_json","underlying_job_ids","file_id","generated_by","created_at","commit_id"],"Outbox":["id","idempotency_key","action_type","target","payload_hash","job_revision","attempt_count","next_attempt","external_id","response_summary","correlation_id","status","created_at","commit_id"],"People":["id","email","display_name","role","active","calendar_id","notification_email","capacity_per_day","available_from","available_to","backup_person_id","company_id","created_at","created_by","updated_at","updated_by","version","source_system","source_record_id","commit_id"],"ReleaseModes":["id","function_id","function_name","mode","mode_record_basis","authorised_job_scope","target_release","planned_target_mode","current_system","fallback","external_ids_protected_reference","activation_time","approved_version","ben_approval_reference","scope_boundary_notes","created_at","created_by","updated_at","updated_by","version","commit_id"]};

function _s14Guard(){var ss=SpreadsheetApp.getActiveSpreadsheet();if(ss.getId()!=='1z7PNZtDdC4Z5eLbmTuQdqp0QpJSmuEvx3QvN3VyNTsc')throw new Error('S14_REFUSED: wrong sheet');var c=JSON.parse(PropertiesService.getScriptProperties().getProperty('S01_CONFIG')||'null');if(!c||c.environment!=='DEV')throw new Error('S14_REFUSED: DEV only');return ss;}
function _s14Sheet(ss,n){var a=ss.getSheets();for(var i=0;i<a.length;i++)if(a[i].getName()===n)return a[i];return null;}
function _s14Read(ss,n){var sh=_s14Sheet(ss,n),h=S14_HEADERS[n];if(!sh||sh.getLastRow()<2)return[];var v=sh.getRange(2,1,sh.getLastRow()-1,Math.min(sh.getLastColumn(),h.length)).getValues(),out=[];for(var r=0;r<v.length;r++){var x={};for(var c=0;c<h.length&&c<v[r].length;c++)x[h[c]]=v[r][c]===''?null:v[r][c];out.push(x);}return out;}
function _s14Insert(ss,n,x){var sh=_s14Sheet(ss,n),h=S14_HEADERS[n],row=sh.getLastRow()+1;if(row>sh.getMaxRows())throw new Error('CAPACITY: '+n);sh.getRange(row,1,1,h.length).setValues([h.map(function(k){var v=x[k];return v===null||v===undefined?'':(typeof v==='string'&&/^[=']/.test(v)?"'"+v:v);})]);SpreadsheetApp.flush();}
function _s14Update(ss,n,id,p){var sh=_s14Sheet(ss,n),h=S14_HEADERS[n],rows=_s14Read(ss,n),ri=-1;for(var i=0;i<rows.length;i++)if(rows[i].id===id){ri=i+2;break;}if(ri<0)throw new Error('Row: '+n+' '+id);var v=sh.getRange(ri,1,1,h.length).getValues()[0];Object.keys(p).forEach(function(k){var j=h.indexOf(k);if(j>=0)v[j]=p[k]===null||p[k]===undefined?'':p[k];});sh.getRange(ri,1,1,h.length).setValues([v]);SpreadsheetApp.flush();}
function _s14Store(ss){return{getSheetId:function(){return ss.getId();},list:function(n){return _s14Read(ss,n);},get:function(n,id){return _s14Read(ss,n).filter(function(x){return x.id===id;})[0]||null;},insert:function(n,x){_s14Insert(ss,n,x);},update:function(n,id,p){_s14Update(ss,n,id,p);}};}
function _s14Result(name,pass,detail){var r={test:name,pass:pass,detail:detail};console.log(JSON.stringify(r,null,2));return r;}

function runS14FixtureDryRun(){var s=_s14Store(_s14Guard());return _s14Result('S14 dry run',true,{fn12:s.list('ReleaseModes').filter(function(r){return r.function_id==='FN-12';}).length});}
function runS14FixtureApply(){var s=_s14Store(_s14Guard()),n='2026-11-01T00:00:00.000Z';function ins(t,x){if(!s.get(t,x.id))s.insert(t,x);}
ins('People',{id:'PERSON-tanya',email:'tanya@dev.example.invalid',display_name:'Tanya',role:'Office',active:true,calendar_id:null,notification_email:null,capacity_per_day:null,available_from:null,available_to:null,backup_person_id:null,company_id:null,created_at:n,created_by:'S14',updated_at:n,updated_by:'S14',version:1,source_system:'S14',source_record_id:null,commit_id:'S14'});
return _s14Result('S14 fixture apply',true,'Fixtures present');}
function runS14FixtureValidate(){var s=_s14Store(_s14Guard());return _s14Result('S14 validate',!!s.get('People','PERSON-tanya'),{});}

function _s14Modes(enable){var s=_s14Store(_s14Guard()),ids=['FN-09','FN-12'];for(var i=0;i<ids.length;i++){var id=ids[i],rows=s.list('ReleaseModes').filter(function(r){return r.function_id===id;});if(rows.length!==1)return _s14Result('S14 modes',false,id+' missing');var r=rows[0];if(r.target_release!=='R4')return _s14Result('S14 modes',false,id+' target must be R4');if(enable&&!(r.mode==='Disabled'&&r.authorised_job_scope==='None')&&!(r.mode==='Automated'&&r.authorised_job_scope==='Pilot'))return _s14Result('S14 modes',false,id+' unexpected state');s.update('ReleaseModes',r.id,{mode:enable?'Automated':'Disabled',authorised_job_scope:enable?'Pilot':'None',updated_at:new Date().toISOString(),updated_by:enable?'S14-enable':'S14-restore',version:Number(r.version||0)+1});}return _s14Result('S14 modes',true,enable?'Enabled Automated/Pilot/R4':'Restored Disabled/None/R4');}
function runS14EnableFunctionsForSyntheticTest(){return _s14Modes(true);}function restoreS14SafeState(){return _s14Modes(false);}

function runS14HappyPathTest(){try{var s=_s14Store(_s14Guard()),n='2026-11-01T00:00:00.000Z';
var job={id:'J-s14-ready',job_id:'SS-S14R-EADY',customer_id:'CUST-s14',display_name:'S14 Reports',sold_submission_id:'S14-sold',booking_submission_id:'S14-booking',sold_at:'2026-10-01T00:00:00.000Z',salesperson_id:null,lead_source:'S14',quote_reference:'Q-S14',presale_file_id:null,finance_route:'Standard',contract_status:'Signed',contract_id:'C-S14',contract_signed_at:'2026-10-15T00:00:00.000Z',contract_evidence_id:null,original_net_pence:400000,original_vat_pence:80000,original_gross_pence:480000,approved_change_pence:null,current_contract_gross_pence:480000,valuation_basis:'Standard',sold_booking_match_status:'Match',customer_details_verified_at:'2026-10-15T00:00:00.000Z',customer_details_verified_by:'PERSON-tanya',deposit_bank_confirmed_at:null,deposit_bank_confirmed_by:null,deposit_bank_reference:null,roof_required:true,electrical_required:false,scaffold_required:false,workflow_stage:'Booked',booking_approved_at:'2026-10-20T00:00:00.000Z',booking_approved_by:'PERSON-tanya',operational_complete_at:null,operational_complete_by:null,customer_happy_at:null,customer_happy_by:null,handover_status:'NotReady',financial_status:'Pending',cancellation_at:null,cancellation_by:null,cancellation_reason:null,archived_at:null,next_action_at:'2026-11-15T00:00:00.000Z',account_policy_version:null,pilot_job:true,release_scope:'R4',created_at:n,created_by:'S14',updated_at:n,updated_by:'S14',version:1,source_system:'S14-fixture',source_record_id:null,commit_id:'S14'};
if(!s.get('Jobs',job.id))s.insert('Jobs',job);
function ins(id,stage,gross,due,status){if(!s.get('InvoiceStages',id))s.insert('InvoiceStages',{id:id,job_id:job.id,stage:stage,amount_net_pence:Math.round(gross/1.2),vat_pence:gross-Math.round(gross/1.2),gross_pence:gross,due_date:due,status:status,xero_invoice_id:null,invoice_number:null,xero_contact_id:null,reference:null,request_id:null,last_synced_at:null,source_status:null,sent_at:null,cancelled_at:null,created_at:n,created_by:'S14',updated_at:n,updated_by:'S14',version:1,source_system:'S14',commit_id:id});}
ins('IS-'+job.id+'-deposit','deposit',120000,'2026-10-20','Confirmed');
ins('IS-'+job.id+'-interim','interim',168000,'2026-11-13','Pending');
if(!s.get('Payments','PAY-deposit'))s.insert('Payments',{id:'PAY-deposit',invoice_stage_id:'IS-'+job.id+'-deposit',xero_payment_id:'XRO-PAY-001',amount_pence:120000,payment_date:'2026-10-25',status:'Confirmed',reconciliation_evidence:null,last_synced_at:null,created_at:n,commit_id:'PAY-deposit'});

var summary=_s14JobFinancialSummary(job.id,s,'2026-11-20');
var inv=_s14InvoiceStatusReport(job.id,s);
var snap=createReportSnapshot(s,'monthly',[job.id],'2026-11-01','2026-11-30');

var pass=summary&&summary.gross===480000&&summary.invoiced===288000&&summary.total_paid===120000&&summary.outstanding===168000&&!summary.financially_complete&&inv.length===2&&snap.created;
return _s14Result('S14 happy path',pass,pass?'PASS. Gross=480000, Invoiced=288000, Paid=120000, Outstanding=168000, FinComplete=false, InvReport=2 stages, Snapshot created.':'FAIL. Gross='+(summary?summary.gross:'?')+' Invoiced='+(summary?summary.invoiced:'?')+' Paid='+(summary?summary.total_paid:'?')+' Outstanding='+(summary?summary.outstanding:'?')+' FinComplete='+(summary?summary.financially_complete:'?')+' InvStages='+inv.length+' Snap='+snap.created);
}catch(e){return _s14Result('S14 happy path',false,String(e.message||e));}}

/* Embedded core */
function _s14LocalDate(v){if(v===null||v===undefined||v==='')return null;if(Object.prototype.toString.call(v)==='[object Date]'){if(isNaN(v.getTime()))return null;return v.toISOString().slice(0,10);}var t=String(v).trim(),m=/^(\d{4})-(\d{2})-(\d{2})/.exec(t);return m?m[1]+'-'+m[2]+'-'+m[3]:null;}
function _s14JobFinancialSummary(jobId,store,asOf){var job=store.get('Jobs',jobId);if(!job)return{job_id:jobId,error:'JOB_NOT_FOUND'};var stages=store.list('InvoiceStages').filter(function(s){return s.job_id===jobId;}),payments=store.list('Payments'),today=asOf||new Date().toISOString().slice(0,10),gross=job.original_gross_pence||job.current_contract_gross_pence||0,invoiced=stages.reduce(function(s,x){return s+(x.gross_pence||0);},0),sp={},totalPaid=0;for(var i=0;i<stages.length;i++){var s=stages[i],ps=payments.filter(function(p){return p.invoice_stage_id===s.id;}),paid=ps.reduce(function(sum,p){return sum+(p.amount_pence||0);},0);sp[s.stage]={invoiced:s.gross_pence||0,paid:paid,outstanding:(s.gross_pence||0)-paid};totalPaid+=paid;}var outstanding=invoiced-totalPaid,overdue=stages.filter(function(s){if(!s.due_date)return false;var d=_s14LocalDate(s.due_date);if(!d)return false;var p=sp[s.stage];return d<today&&p&&p.outstanding>0;}),overdueAmt=overdue.reduce(function(sum,s){var p=sp[s.stage];return sum+(p?p.outstanding:0);},0);return{job_id:jobId,as_of:today,gross:gross,stages_count:stages.length,invoiced:invoiced,total_paid:totalPaid,outstanding:outstanding,overdue_amount:overdueAmt,overdue_stages:overdue.map(function(s){return s.stage;}),financially_complete:!!job.operational_complete_at&&['deposit','interim','final'].every(function(s){return sp[s]&&sp[s].outstanding===0;})};}
function _s14ReconcilePayments(jobId,store){var stages=store.list('InvoiceStages').filter(function(s){return s.job_id===jobId;}),payments=store.list('Payments'),ex=[];for(var i=0;i<stages.length;i++){var s=stages[i],ps=payments.filter(function(p){return p.invoice_stage_id===s.id;}),tp=ps.reduce(function(sum,p){return sum+(p.amount_pence||0);},0);if(tp>(s.gross_pence||0))ex.push({type:'OVERPAYMENT',stage:s.stage});var refs=ps.filter(function(p){return p.xero_payment_id;}).map(function(p){return p.xero_payment_id;}),dupes=refs.filter(function(r,i){return refs.indexOf(r)!==i;});for(var j=0;j<dupes.length;j++)ex.push({type:'DUPLICATE_PAYMENT_REF',stage:s.stage,reference:dupes[j]});}return{job_id:jobId,exceptions:ex,exception_count:ex.length,needs_review:ex.length>0};}
function _s14InvoiceStatusReport(jobId,store){var stages=store.list('InvoiceStages').filter(function(s){return s.job_id===jobId;}),today=new Date().toISOString().slice(0,10);return stages.map(function(s){var d=_s14LocalDate(s.due_date),od=d&&d<today&&s.status!=='Confirmed',ps=store.list('Payments').filter(function(p){return p.invoice_stage_id===s.id;}),paid=ps.reduce(function(sum,p){return sum+(p.amount_pence||0);},0);return{stage_id:s.id,stage:s.stage,gross:s.gross_pence||0,due_date:d,status:s.status,paid:paid,outstanding:(s.gross_pence||0)-paid,overdue:od};});}
function createReportSnapshot(store,type,jobIds,ps,pe){var n=new Date().toISOString(),id='RS-'+type+'-'+ps,ex=store.get('ReportSnapshots',id);if(ex)return{created:false,snapshot:ex};var sums=jobIds.map(function(jid){return _s14JobFinancialSummary(jid,store,pe);}),t={total_gross:sums.reduce(function(s,r){return s+(r.gross||0);},0),total_invoiced:sums.reduce(function(s,r){return s+(r.invoiced||0);},0),total_paid:sums.reduce(function(s,r){return s+(r.total_paid||0);},0),total_outstanding:sums.reduce(function(s,r){return s+(r.outstanding||0);},0),total_overdue:sums.reduce(function(s,r){return s+(r.overdue_amount||0);},0),job_count:sums.length,financially_complete:sums.filter(function(r){return r.financially_complete;}).length};store.insert('ReportSnapshots',{id:id,period_start:ps,period_end:pe,as_of_at:n,policy_version:'S14-DEV-1.0',report_type:type,totals_json:JSON.stringify(t),underlying_job_ids:JSON.stringify(jobIds),file_id:null,generated_by:'S14',created_at:n,commit_id:id});return{created:true,snapshot_id:id,totals:t};}
