/* S11 planners, moves, allocations and Calendar capture boundary. */
'use strict';

const S11_DEV_SHEET_ID='1z7PNZtDdC4Z5eLbmTuQdqp0QpJSmuEvx3QvN3VyNTsc';

function _s11LocalDate(value){
  if(value===null||value===undefined||value==='')throw new Error('S11_DATE_INVALID: date value is required');
  if(Object.prototype.toString.call(value)==='[object Date]'){
    if(isNaN(value.getTime()))throw new Error('S11_DATE_INVALID: invalid Date object');
    if(typeof Utilities!=='undefined'&&Utilities.formatDate)return Utilities.formatDate(value,'Europe/London','yyyy-MM-dd');
    return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(value);
  }
  const text=String(value).trim(),m=/^(\d{4})-(\d{2})-(\d{2})(?:$|T)/.exec(text);
  if(!m)throw new Error('S11_DATE_INVALID: expected YYYY-MM-DD or ISO timestamp');
  const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]),check=new Date(Date.UTC(y,mo-1,d));
  if(check.getUTCFullYear()!==y||check.getUTCMonth()!==mo-1||check.getUTCDate()!==d)throw new Error('S11_DATE_INVALID: invalid calendar date');
  if(text.length>10&&!Number.isFinite(new Date(text).getTime()))throw new Error('S11_DATE_INVALID: invalid ISO timestamp');
  return m[1]+'-'+m[2]+'-'+m[3];
}
function _s11Dates(start,end){const a=_s11LocalDate(start),b=_s11LocalDate(end),d=new Date(a+'T12:00:00Z'),last=new Date(b+'T12:00:00Z'),out=[];if(d>last)throw new Error('S11_DATE_INVALID: end before start');while(d<=last){out.push(d.toISOString().slice(0,10));d.setUTCDate(d.getUTCDate()+1);}return out;}
function _s11NextDate(value){const d=new Date(_s11LocalDate(value)+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+1);return d.toISOString().slice(0,10);}
function _s11Hash(value){const s=JSON.stringify(value);let h=0;for(let i=0;i<s.length;i++){h=((h<<5)-h)+s.charCodeAt(i);h|=0;}return'h'+(h>>>0).toString(16).padStart(8,'0');}
function _s11AssertScope(jobId,store,ids=['FN-01','FN-02']){if(!store.getSheetId||store.getSheetId()!==S11_DEV_SHEET_ID||!store.getEnvironment||store.getEnvironment()!=='DEV')throw new Error('S11_REFUSED: DEV only / wrong sheet');const job=store.get('Jobs',jobId);if(!job||job.pilot_job!==true||job.release_scope!=='R2'||!/^S11/.test(job.source_system||''))throw new Error('S11_REFUSED: synthetic S11 R2 pilot job required');for(const id of ids){const rows=store.list('ReleaseModes').filter(r=>r.function_id===id),release=id==='FN-01'?'R1':'R2';if(rows.length!==1||rows[0].mode!=='Automated'||rows[0].authorised_job_scope!=='Pilot'||rows[0].target_release!==release)throw new Error('S11_REFUSED: '+id+' must be Automated/Pilot/'+release);}return job;}
function _s11AssertR1Scope(jobId,store){if(!store.getSheetId||store.getSheetId()!==S11_DEV_SHEET_ID||!store.getEnvironment||store.getEnvironment()!=='DEV')throw new Error('S11_REFUSED: DEV only / wrong sheet');const job=store.get('Jobs',jobId),m=store.list('ReleaseModes').filter(r=>r.function_id==='FN-01');if(!job||job.pilot_job!==true||job.release_scope!=='R1')throw new Error('S11_REFUSED: R1 pilot job required');if(m.length!==1||m[0].mode!=='Automated'||m[0].authorised_job_scope!=='Pilot'||m[0].target_release!=='R1')throw new Error('S11_REFUSED: FN-01 must be Automated/Pilot/R1');return job;}
function _s11Command(store,input,entityType,entityId,changes){if(!input.command_id)throw new Error('S11_REVIEW: command_id required');const id='CJ-S11-'+input.command_id,encoded=JSON.stringify(changes),existing=store.get('CommitJournal',id);if(existing){if(existing.command_id!==input.command_id||existing.entity_type!==entityType||existing.entity_id!==entityId||existing.changes_json!==encoded)throw new Error('S11_REVIEW: conflicting command identity');return{replay:true,journal:existing};}const now=input.at||new Date().toISOString(),row={id,commit_id:'S11-'+input.command_id,state:'Prepared',command_id:input.command_id,entity_type:entityType,entity_id:entityId,expected_version:input.expected_version===undefined?null:input.expected_version,changes_json:encoded,prepared_at:now,committed_at:null,created_at:now};store.insert('CommitJournal',row);return{replay:false,journal:row};}
function _s11ExistingCommand(store,input,entityType,entityId,changes){if(!input.command_id)throw new Error('S11_REVIEW: command_id required');const existing=store.get('CommitJournal','CJ-S11-'+input.command_id);if(!existing)return null;if(existing.command_id!==input.command_id||existing.entity_type!==entityType||existing.entity_id!==entityId||existing.changes_json!==JSON.stringify(changes))throw new Error('S11_REVIEW: conflicting command identity');return existing;}
function _s11Commit(store,commandId,at){store.update('CommitJournal','CJ-S11-'+commandId,{state:'Committed',committed_at:at||new Date().toISOString()});}
function _s11Settings(store){const tz=store.list('Settings').filter(s=>s.key==='office.timezone').sort((a,b)=>b.version-a.version)[0],days=store.list('Settings').filter(s=>s.key==='office.staffed_weekdays').sort((a,b)=>b.version-a.version)[0];if(!tz||tz.typed_value!=='Europe/London'||!days)throw new Error('S11_CONFIG: Europe/London staffed-day settings required');let weekdays;try{weekdays=JSON.parse(days.typed_value);}catch(e){throw new Error('S11_CONFIG: invalid staffed weekdays');}if(!Array.isArray(weekdays))throw new Error('S11_CONFIG: invalid staffed weekdays');return{weekdays};}
function _s11ValidatePerson(store,personId,start,end){const p=store.get('People',personId);if(!p||p.active!==true||p.role!=='Installer')return{ready:false,reason:'INSTALLER_INACTIVE_OR_WRONG_ROLE'};if(!Number.isInteger(Number(p.capacity_per_day))||Number(p.capacity_per_day)<1)return{ready:false,reason:'CAPACITY_NOT_CONFIGURED'};const a=_s11LocalDate(start),b=_s11LocalDate(end);if(p.available_from&&a<_s11LocalDate(p.available_from))return{ready:false,reason:'INSTALLER_UNAVAILABLE'};if(p.available_to&&b>_s11LocalDate(p.available_to))return{ready:false,reason:'INSTALLER_UNAVAILABLE'};return{ready:true,person:p};}
function _s11Capacity(store,person,start,end,excludeAllocationId){const dates=_s11Dates(start,end),holidays=store.list('Holidays').filter(h=>h.office_closed===true).map(h=>_s11LocalDate(h.local_date)),settings=_s11Settings(store),p=_s11ValidatePerson(store,person.id,start,end);if(!p.ready)return p;for(const date of dates){const day=new Date(date+'T12:00:00Z').getUTCDay();if(holidays.includes(date))return{ready:false,reason:'OFFICE_HOLIDAY',date};if(!settings.weekdays.includes(day))continue;const used=store.list('Allocations').filter(a=>a.active===true&&a.person_id===person.id&&a.id!==excludeAllocationId&&a.start_at&&a.end_at&&_s11LocalDate(a.start_at)<=date&&_s11LocalDate(a.end_at)>=date).length;if(used>=Number(person.capacity_per_day))return{ready:false,reason:'CAPACITY_CONFLICT',date,used,capacity:Number(person.capacity_per_day)};}return{ready:true};}
function _s11CalendarPayload(job,wp,allocation){return{job_id:job.id,work_package_id:wp.id,allocation_id:allocation.id,title:job.display_name+' — '+wp.trade,start_at:_s11LocalDate(allocation.start_at),end_at:_s11NextDate(allocation.end_at),all_day:true,internal_reference:job.id,guests:[]};}
function _s11QueueCalendar(store,job,wp,allocation,commandId,kind,existingLink){const person=store.get('People',allocation.person_id);if(!person||!person.calendar_id||person.calendar_id==='NOT_CONFIGURED')throw new Error('S11_CONFIG: verified synthetic calendar_id required');const payload=_s11CalendarPayload(job,wp,allocation),linkId=existingLink?existingLink.id:'CL-'+allocation.id,outboxId='OUT-S11-'+commandId+'-'+kind,key='S11-CALENDAR-'+commandId+'-'+kind,hash=_s11Hash(payload),existingOut=store.get('Outbox',outboxId);if(existingOut){if(existingOut.idempotency_key!==key||existingOut.payload_hash!==hash)throw new Error('S11_REVIEW: conflicting Calendar action');return{link:store.get('CalendarLinks',linkId),outbox:existingOut,created:false};}const now=new Date().toISOString();let link=existingLink;if(!link){link={id:linkId,job_id:job.id,allocation_id:allocation.id,scaffold_activity_id:null,calendar_id:person.calendar_id,external_event_id:null,event_uid:null,producer:'NewSystem',entity_revision:wp.revision,last_synced_revision:0,status:'Pending',start_at:payload.start_at,end_at:payload.end_at,all_day:true,guest_person_ids:null,description_snapshot:JSON.stringify(payload),last_attempt_at:null,last_success_at:null,error:null,outbox_id:outboxId,created_at:now,created_by:'S11',updated_at:now,updated_by:'S11',version:1,commit_id:'S11-'+commandId};store.insert('CalendarLinks',link);}else{const patch={allocation_id:allocation.id,calendar_id:person.calendar_id,entity_revision:wp.revision,status:link.external_event_id?'UpdatePending':'Pending',start_at:payload.start_at,end_at:payload.end_at,description_snapshot:JSON.stringify(payload),outbox_id:outboxId,updated_at:now,updated_by:'S11',version:Number(link.version||0)+1};store.update('CalendarLinks',link.id,patch);link=store.get('CalendarLinks',link.id);}const out={id:outboxId,idempotency_key:key,action_type:link.external_event_id?'CalendarUpdate':'CalendarCreate',target:link.calendar_id,payload_hash:hash,job_revision:wp.revision,attempt_count:0,next_attempt:null,external_id:link.external_event_id||null,response_summary:'CAPTURE_ONLY: no Calendar API call',correlation_id:commandId,status:'Pending',created_at:now,commit_id:'S11-'+commandId};store.insert('Outbox',out);return{link,outbox:out,created:true,payload};}
function _s11QueueCalendarCancel(store,link,commandId,revision){if(!link)return null;const id='OUT-S11-'+commandId+'-OLD_INSTALLER',payload={calendar_link_id:link.id,external_event_id:link.external_event_id||null,action:'Cancel'},hash=_s11Hash(payload),existing=store.get('Outbox',id);if(existing){if(existing.payload_hash!==hash)throw new Error('S11_REVIEW: conflicting Calendar cancellation');return existing;}const now=new Date().toISOString();store.update('CalendarLinks',link.id,{status:'Cancelled',entity_revision:revision,outbox_id:id,updated_at:now,updated_by:'S11',version:Number(link.version||0)+1});const out={id,idempotency_key:'S11-CALENDAR-'+commandId+'-OLD_INSTALLER',action_type:'CalendarCancel',target:link.calendar_id,payload_hash:hash,job_revision:revision,attempt_count:0,next_attempt:null,external_id:link.external_event_id||null,response_summary:'CAPTURE_ONLY: no Calendar API call',correlation_id:commandId,status:'Pending',created_at:now,commit_id:'S11-'+commandId};store.insert('Outbox',out);return out;}
function _s11Audit(store,type,id,action,before,after,input){const now=input.at||new Date().toISOString();store.insert('AuditEvents',{id:'AUD-S11-'+input.command_id+'-'+type+'-'+id,entity_type:type,entity_id:id,action,before_json:before?JSON.stringify(before):null,after_json:JSON.stringify(after),initiating_actor:input.actor,executing_service:'S11',timestamp:now,correlation_id:input.command_id,reason:input.reason||null,commit_id:'S11-'+input.command_id,created_at:now});}

function _s11UpdatePlannedDates(input,store){
  const job=_s11AssertR1Scope(input.job_id,store),wp=store.get('WorkPackages',input.work_package_id);
  if(!wp||wp.job_id!==job.id)throw new Error('S11_REVIEW: work package linkage invalid');
  const changes={planned_start:_s11LocalDate(input.planned_start),planned_end:_s11LocalDate(input.planned_end)};_s11Dates(changes.planned_start,changes.planned_end);
  const existing=_s11ExistingCommand(store,input,'WorkPackages',wp.id,changes);if(existing){if(existing.state!=='Committed')throw new Error('S11_RECOVERY_REQUIRED: incomplete planner command');return{status:'Replayed',work_package:wp,external_calls:0};}
  if(Number(wp.version)!==Number(input.expected_version))throw new Error('S11_STALE: work package version');
  _s11Command(store,input,'WorkPackages',wp.id,changes);const now=input.at||new Date().toISOString(),after=Object.assign({},wp,changes,{revision:Number(wp.revision||0)+1,updated_at:now,updated_by:input.actor,version:Number(wp.version)+1});
  store.update('WorkPackages',wp.id,{planned_start:after.planned_start,planned_end:after.planned_end,revision:after.revision,updated_at:now,updated_by:input.actor,version:after.version,commit_id:'S11-'+input.command_id});
  _s11Audit(store,'WorkPackages',wp.id,'PlanDates',wp,after,input);_s11Commit(store,input.command_id,now);return{status:'Updated',work_package:store.get('WorkPackages',wp.id),external_calls:0};
}

function _s11PlanWorkPackage(input,store){
  /* S15: stop normal work during cancellation and controlled reopen review. */
  var S15_job = store.get('Jobs',input.job_id); if (S15_job && (S15_job.cancellation_at || ['CancellationInProgress','Cancelled'].includes(S15_job.workflow_stage) || store.list('Tasks').some(function(t){return t.job_id===S15_job.id&&t.template_code==='S15-REOPEN-REVIEW'&&!['Complete','NotRequired'].includes(t.status);}))) throw new Error('S15_REVIEW: normal work suppressed');
const job=_s11AssertScope(input.job_id,store),wp=store.get('WorkPackages',input.work_package_id);if(!wp||wp.job_id!==job.id)throw new Error('S11_REVIEW: work package linkage invalid');const allocationId=input.allocation_id||'ALLOC-S11-'+input.command_id,changes={job_id:job.id,work_package_id:wp.id,person_id:input.person_id,role:input.role||'Lead',start_at:_s11LocalDate(input.start_at),end_at:_s11LocalDate(input.end_at),allocation_id:allocationId};if(_s11ExistingCommand(store,input,'WorkPackages',wp.id,changes))return{status:'Replayed',created:false,allocation:store.get('Allocations',allocationId),calendar:store.list('CalendarLinks').filter(c=>c.allocation_id===allocationId)[0]||null};if(Number(wp.version)!==Number(input.expected_version))throw new Error('S11_STALE: work package version');const personCheck=_s11ValidatePerson(store,input.person_id,input.start_at,input.end_at);if(!personCheck.ready)return{status:'NeedsReview',reason:personCheck.reason};const cap=_s11Capacity(store,personCheck.person,input.start_at,input.end_at,null);if(!cap.ready)return{status:'NeedsReview',reason:cap.reason,detail:cap};_s11Command(store,input,'WorkPackages',wp.id,changes);const now=input.at||new Date().toISOString(),newWp={...wp,planned_start:changes.start_at,planned_end:changes.end_at,status:'Scheduled',revision:Number(wp.revision||0)+1,updated_at:now,updated_by:input.actor,version:Number(wp.version)+1};store.update('WorkPackages',wp.id,{planned_start:newWp.planned_start,planned_end:newWp.planned_end,status:newWp.status,revision:newWp.revision,updated_at:now,updated_by:input.actor,version:newWp.version});const allocation={id:allocationId,work_package_id:wp.id,person_id:input.person_id,role:changes.role,start_at:changes.start_at,end_at:changes.end_at,active:true,replaced_allocation_id:null,cancellation_reason:null,calendar_link_id:'CL-'+allocationId,created_at:now,created_by:input.actor,updated_at:now,updated_by:input.actor,version:1,source_system:'S11',commit_id:'S11-'+input.command_id};store.insert('Allocations',allocation);const cal=_s11QueueCalendar(store,job,newWp,allocation,input.command_id,'UPSERT',null);_s11Audit(store,'WorkPackages',wp.id,'Plan',wp,newWp,input);_s11Commit(store,input.command_id,now);return{status:'Planned',created:true,allocation,calendar:cal};}

function _s11MoveWorkPackage(input,store){
  /* S15: stop normal work during cancellation and controlled reopen review. */
  var S15_job = store.get('Jobs',input.job_id); if (S15_job && (S15_job.cancellation_at || ['CancellationInProgress','Cancelled'].includes(S15_job.workflow_stage) || store.list('Tasks').some(function(t){return t.job_id===S15_job.id&&t.template_code==='S15-REOPEN-REVIEW'&&!['Complete','NotRequired'].includes(t.status);}))) throw new Error('S15_REVIEW: normal work suppressed');
const job=_s11AssertScope(input.job_id,store),wp=store.get('WorkPackages',input.work_package_id),allocation=store.get('Allocations',input.allocation_id);if(!wp||wp.job_id!==job.id||!allocation||allocation.work_package_id!==wp.id||allocation.active!==true)throw new Error('S11_REVIEW: active allocation linkage invalid');const changes={work_package_id:wp.id,allocation_id:allocation.id,start_at:_s11LocalDate(input.start_at),end_at:_s11LocalDate(input.end_at),reason:input.reason};if(_s11ExistingCommand(store,input,'WorkPackages',wp.id,changes))return{status:'Replayed',created:false,allocation};if(Number(wp.version)!==Number(input.expected_version))throw new Error('S11_STALE: work package version');if(!input.reason)throw new Error('S11_REVIEW: move reason required');const p=store.get('People',allocation.person_id),cap=_s11Capacity(store,p,input.start_at,input.end_at,allocation.id);if(!cap.ready)return{status:'NeedsReview',reason:cap.reason,detail:cap};_s11Command(store,input,'WorkPackages',wp.id,changes);const now=input.at||new Date().toISOString(),newWp={...wp,planned_start:changes.start_at,planned_end:changes.end_at,revision:Number(wp.revision)+1,updated_at:now,updated_by:input.actor,version:Number(wp.version)+1},newAllocation={...allocation,start_at:changes.start_at,end_at:changes.end_at,updated_at:now,updated_by:input.actor,version:Number(allocation.version)+1};store.update('WorkPackages',wp.id,{planned_start:newWp.planned_start,planned_end:newWp.planned_end,revision:newWp.revision,updated_at:now,updated_by:input.actor,version:newWp.version});store.update('Allocations',allocation.id,{start_at:newAllocation.start_at,end_at:newAllocation.end_at,updated_at:now,updated_by:input.actor,version:newAllocation.version});const link=store.get('CalendarLinks',allocation.calendar_link_id),cal=_s11QueueCalendar(store,job,newWp,newAllocation,input.command_id,'MOVE',link);_s11Audit(store,'WorkPackages',wp.id,'Move',wp,newWp,input);_s11Audit(store,'Allocations',allocation.id,'Move',allocation,newAllocation,input);_s11Commit(store,input.command_id,now);return{status:'Moved',created:true,allocation:newAllocation,calendar:cal};}

function _s11ChangeInstaller(input,store){
  /* S15: stop normal work during cancellation and controlled reopen review. */
  var S15_job = store.get('Jobs',input.job_id); if (S15_job && (S15_job.cancellation_at || ['CancellationInProgress','Cancelled'].includes(S15_job.workflow_stage) || store.list('Tasks').some(function(t){return t.job_id===S15_job.id&&t.template_code==='S15-REOPEN-REVIEW'&&!['Complete','NotRequired'].includes(t.status);}))) throw new Error('S15_REVIEW: normal work suppressed');
const job=_s11AssertScope(input.job_id,store),wp=store.get('WorkPackages',input.work_package_id),old=store.get('Allocations',input.old_allocation_id);if(!wp||wp.job_id!==job.id||!old||old.work_package_id!==wp.id)throw new Error('S11_REVIEW: allocation linkage invalid');const newId=input.allocation_id||'ALLOC-S11-'+input.command_id,changes={work_package_id:wp.id,old_allocation_id:old.id,new_allocation_id:newId,person_id:input.person_id,mode:input.mode,reason:input.reason};if(_s11ExistingCommand(store,input,'Allocations',old.id,changes))return{status:'Replayed',created:false,allocation:store.get('Allocations',newId)};if(old.active!==true)throw new Error('S11_REVIEW: active allocation linkage invalid');if(Number(wp.version)!==Number(input.expected_version))throw new Error('S11_STALE: work package version');if(!['Replace','Add'].includes(input.mode)||!input.reason)throw new Error('S11_REVIEW: mode and reason required');const check=_s11ValidatePerson(store,input.person_id,old.start_at,old.end_at);if(!check.ready)return{status:'NeedsReview',reason:check.reason};const cap=_s11Capacity(store,check.person,old.start_at,old.end_at,null);if(!cap.ready)return{status:'NeedsReview',reason:cap.reason};_s11Command(store,input,'Allocations',old.id,changes);const now=input.at||new Date().toISOString(),nextRevision=Number(wp.revision)+1,newAllocation={id:newId,work_package_id:wp.id,person_id:input.person_id,role:input.mode==='Add'?(input.role||'Second'):old.role,start_at:old.start_at,end_at:old.end_at,active:true,replaced_allocation_id:input.mode==='Replace'?old.id:null,cancellation_reason:null,calendar_link_id:'CL-'+newId,created_at:now,created_by:input.actor,updated_at:now,updated_by:input.actor,version:1,source_system:'S11',commit_id:'S11-'+input.command_id};if(input.mode==='Replace'){store.update('Allocations',old.id,{active:false,cancellation_reason:input.reason,updated_at:now,updated_by:input.actor,version:Number(old.version)+1});_s11QueueCalendarCancel(store,store.get('CalendarLinks',old.calendar_link_id),input.command_id,nextRevision);}store.insert('Allocations',newAllocation);store.update('WorkPackages',wp.id,{revision:nextRevision,updated_at:now,updated_by:input.actor,version:Number(wp.version)+1});const updatedWp={...wp,revision:nextRevision,version:Number(wp.version)+1},cal=_s11QueueCalendar(store,job,updatedWp,newAllocation,input.command_id,'NEW_INSTALLER',null);_s11Audit(store,'Allocations',old.id,input.mode==='Replace'?'ReplaceInstaller':'AddInstaller',old,newAllocation,input);_s11Commit(store,input.command_id,now);return{status:input.mode==='Replace'?'Replaced':'Added',created:true,allocation:newAllocation,calendar:cal};}

function _s11BuildPlanner(store,start,weeks){const from=_s11LocalDate(start),d=new Date(from+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+Number(weeks)*7-1);const to=d.toISOString().slice(0,10),rows=[];for(const wp of store.list('WorkPackages').filter(w=>w.planned_start&&w.planned_end&&_s11LocalDate(w.planned_end)>=from&&_s11LocalDate(w.planned_start)<=to&&w.status!=='Cancelled'))for(const a of store.list('Allocations').filter(x=>x.work_package_id===wp.id&&x.active===true))rows.push({job_id:wp.job_id,work_package_id:wp.id,allocation_id:a.id,person_id:a.person_id,trade:wp.trade,start_at:_s11LocalDate(a.start_at),end_at:_s11LocalDate(a.end_at)});return{from,to,weeks:Number(weeks),rows};}

module.exports={S11_DEV_SHEET_ID,localDate:_s11LocalDate,planWorkPackage:_s11PlanWorkPackage,moveWorkPackage:_s11MoveWorkPackage,changeInstaller:_s11ChangeInstaller,updatePlannedDates:_s11UpdatePlannedDates,buildPlanner:_s11BuildPlanner};
